# -*- coding: utf-8 -*-
"""BLIP_NSGA_Random_Finalv3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NpkGPoJOuB8sT8Zk9jTev_aK-paig6Zi
"""

#from transformers import BlipProcessor, BlipForConditionalGeneration
from __future__ import annotations



from dataclasses import dataclass
from typing import Dict, Iterable, List, Optional, Tuple
import pandas as pd  
try:
    from jmetal.core.quality_indicator import HyperVolume, InvertedGenerationalDistance
except ImportError:
    from jmetal.component.quality_indicator import HyperVolume, InvertedGenerationalDistance



import matplotlib.pyplot as plt
import seaborn as sns # Optional, for nicer styling

import os
import sys
import copy
import json
import csv
import random
import numpy as np
import torch
import cv2
from PIL import Image
from datetime import datetime
from pathlib import Path
import time

# Fix for numpy/scipy incompatibility
#!pip install numpy==1.26.4 scipy==1.16.3 --force-reinstall

# jMetalPy imports
from jmetal.core.problem import FloatProblem
from jmetal.core.solution import FloatSolution
from jmetal.core.algorithm import Algorithm
from jmetal.util.comparator import ObjectiveComparator


# jMetalPy imports
from jmetal.algorithm.multiobjective.nsgaii import NSGAII
from jmetal.operator.crossover import SBXCrossover
from jmetal.operator.mutation import PolynomialMutation
from jmetal.operator.selection import BinaryTournamentSelection
from jmetal.util.comparator import RankingAndCrowdingDistanceComparator
from jmetal.util.termination_criterion import StoppingByEvaluations

from jmetal.algorithm.multiobjective.random_search import RandomSearch
from jmetal.core.problem import FloatProblem
from jmetal.core.solution import FloatSolution
from jmetal.util.termination_criterion import StoppingByEvaluations

import re
from transformers import InstructBlipProcessor, InstructBlipForConditionalGeneration

# device
if torch.cuda.is_available():
    device = torch.device("cuda:0")
elif torch.backends.mps.is_available() and torch.backends.mps.is_built():
    device = torch.device("mps")
else:
    device = torch.device("cpu")

MODEL_NAME = "Salesforce/instructblip-vicuna-7b"

processor = InstructBlipProcessor.from_pretrained(MODEL_NAME)
model = InstructBlipForConditionalGeneration.from_pretrained(
    MODEL_NAME,
    torch_dtype=torch.float16 if device.type == "cuda" else torch.float32,
    low_cpu_mem_usage=True).to(device)
model.eval()

cat_names = ["Trash", "Objects", "Animal", "Vegetation"]

#CATEGORY_PROMPT = "Identify and list all visible objects in this underwater image in four categories: (1) Trash (2) Objects (3) Animals (4) Vegetation. For each category, list the detected items with counts. If a category is definitely absent, write None."
CATEGORY_PROMPT = "Identify and list all visible objects in this underwater image in four categories:1. Animals 2. Vegetation 3. Trash 4. Objects. For each category: list the objects with counts. If a category is absent, write 'None'."

ANIMAL_WORDS = {
    "fish", "fishes", "crab", "crabs", "jellyfish", "lobster", "lobsters", "octopus",
    "octopi", "shrimp", "squid", "stingray", "ray", "turtle", "turtles", "urchin",
    "urchins", "starfish", "shell", "shells", "sponge", "sponges", "coral", "corals",
    "animal", "animals"
}

VEGETATION_WORDS = {
    "plant", "plants", "algae", "seaweed", "seagrass", "grass", "kelp", "vegetation"
}

TRASH_WORDS = {
    "bag", "bags", "bottle", "bottles", "cup", "cups", "container", "containers",
    "wrapper", "wrappers", "lid", "lids", "net", "nets", "rope", "ropes", "pipe", "pipes",
    "cable", "cables", "clothing", "boot", "boots", "tire", "tires", "tyre", "tyres",
    "cardboard", "branch", "branches", "furniture", "wood", "paper", "tube", "tubes",
    "brick", "bricks", "wreckage", "trash", "garbage", "debris", "plastic", "plastics",
    "can", "cans"
}

OBJECT_WORDS = {
    "object", "objects", "rov", "vehicle", "boat", "barge", "submarine", "crane",
    "tool", "tools", "box", "boxes", "metal", "equipment"
}

NUMBER_WORDS = {
    "a": 1, "an": 1, "one": 1, "two": 2, "three": 3, "four": 4, "five": 5,
    "six": 6, "seven": 7, "eight": 8, "nine": 9, "ten": 10
}

def _word_to_num(token: str):
    token = token.strip().lower()
    if token.isdigit():
        return int(token)
    return NUMBER_WORDS.get(token)

def _parse_count_from_chunk(chunk: str) -> int:
    chunk = chunk.lower().strip()

    m = re.search(r"\b(\d+)\b", chunk)
    if m:
        return int(m.group(1))

    for w, v in NUMBER_WORDS.items():
        if re.search(rf"\b{re.escape(w)}\b", chunk):
            return v

    if chunk and chunk not in {"none", "no", "nothing", "not visible", "not present"}:
        return 1
    return 0

def _count_items_in_text(text: str, vocab: set) -> int:
    text = text.lower()
    total = 0

    # split by commas / semicolons
    chunks = re.split(r"[;,]", text)
    for chunk in chunks:
        if any(re.search(rf"\b{re.escape(word)}\b", chunk) for word in vocab):
            total += _parse_count_from_chunk(chunk)

    # fallback: if category word exists but no count was found, count as 1
    if total == 0 and any(re.search(rf"\b{re.escape(word)}\b", text) for word in vocab):
        total = 1

    return total

def extract_category_counts(blip_output: str) -> dict:
    """
    Returns:
        {"Trash": int, "Objects": int, "Animal": int, "Vegetation": int}
    """
    text = blip_output.strip()
    lower = text.lower()

    counts = {"Trash": 0, "Objects": 0, "Animal": 0, "Vegetation": 0}

    line_map = {
        "animals:": ("Animal", ANIMAL_WORDS),
        "vegetation:": ("Vegetation", VEGETATION_WORDS),
        "trash:": ("Trash", TRASH_WORDS),
        "objects:": ("Objects", OBJECT_WORDS),
    }

    found_structured = False

    for prefix, (cat, vocab) in line_map.items():
        if prefix in lower:
            found_structured = True
            part = lower.split(prefix, 1)[1]
            part = part.split("\n", 1)[0].strip()
            if part not in {"none", "no", "nothing", "not visible", "not present"}:
                counts[cat] = _count_items_in_text(part, vocab)

    # fallback if model does not follow requested 4-line format
    #print("Fallback Structure Detected...!")
    if not found_structured:
        counts["Animal"] = _count_items_in_text(lower, ANIMAL_WORDS)
        counts["Vegetation"] = _count_items_in_text(lower, VEGETATION_WORDS)
        counts["Trash"] = _count_items_in_text(lower, TRASH_WORDS)
        counts["Objects"] = _count_items_in_text(lower, OBJECT_WORDS)

    return counts

# ============================================================================
# UPDATED PREDICTION LOGIC
# ============================================================================

def generate_blip_prediction(image, question=CATEGORY_PROMPT, max_new_tokens=80):
    if isinstance(image, str):
        image = Image.open(image).convert("RGB")
    else:
        image = image.convert("RGB")

    if device.type == "cuda":
        inputs = processor(images=image, text=question, return_tensors="pt").to(device, torch.float16)
    else:
        inputs = processor(images=image, text=question, return_tensors="pt").to(device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False
        )

    generated_text = processor.batch_decode(outputs, skip_special_tokens=True)[0].strip()

    if generated_text.lower().startswith(question.lower()):
        generated_text = generated_text[len(question):].strip(": ").strip()

    category_counts = extract_category_counts(generated_text)

    return {
        "caption": generated_text,
        "categories": category_counts
    }

def generate_marinegpt_prediction(image, chat=None):
    return generate_blip_prediction(image)

# ============================================================================
# IMAGE TRANSFORMATION FUNCTIONS (MMR) - SAME AS BEFORE
# ============================================================================

def rotate_image(image: Image.Image, angle: float) -> Image.Image:
    return image.rotate(angle, expand=False, fillcolor=(0, 0, 0))

def scale_image(image: Image.Image, zoom_level: float) -> Image.Image:
    width, height = image.size
    new_width = int(width * zoom_level)
    new_height = int(height * zoom_level)
    resized = image.resize((new_width, new_height), Image.LANCZOS)
    if zoom_level > 1.0:
        left = (new_width - width) // 2
        top = (new_height - height) // 2
        return resized.crop((left, top, left + width, top + height))
    else:
        new_image = Image.new('RGB', (width, height), (0, 0, 0))
        paste_x = (width - new_width) // 2
        paste_y = (height - new_height) // 2
        new_image.paste(resized, (paste_x, paste_y))
        return new_image

def apply_histogram_equalization(image: Image.Image, clip_limit: float) -> Image.Image:
    img_array = np.array(image)
    lab = cv2.cvtColor(img_array, cv2.COLOR_RGB2LAB)
    l, a, b = cv2.split(lab)
    clahe = cv2.createCLAHE(clipLimit=clip_limit, tileGridSize=(16, 16))
    l_clahe = clahe.apply(l)
    lab_clahe = cv2.merge([l_clahe, a, b])
    img_clahe = cv2.cvtColor(lab_clahe, cv2.COLOR_LAB2RGB)
    return Image.fromarray(img_clahe)

def downsample_image(image: Image.Image, scale_factor: float) -> Image.Image:
    width, height = image.size
    intermediate_w = int(width * scale_factor)
    intermediate_h = int(height * scale_factor)
    downsampled = image.resize((intermediate_w, intermediate_h), Image.NEAREST)
    return downsampled.resize((width, height), Image.NEAREST)

def shear_image(image: Image.Image, h_shear: float) -> Image.Image:

    # Applies only horizontal shear to the image.
    # h_shear: Shear factor (e.g., 0.2 means x' = x + 0.2*y)

    img_array = np.array(image)
    height, width = img_array.shape[:2]

    # Shear matrix:
    # [1, h_shear, 0] -> x_new = x + h_shear * y
    # [0, 1,       0] -> y_new = y (No vertical change)
    shear_matrix = np.array([[1, h_shear, 0], [0, 1, 0]], dtype=np.float32)

    sheared = cv2.warpAffine(img_array, shear_matrix, (width, height), borderMode=cv2.BORDER_CONSTANT, borderValue=(0, 0, 0))
    return Image.fromarray(sheared)

def translate_image(image: Image.Image, h_shift_pct: float) -> Image.Image:

    # Applies only horizontal translation to the image.
    # h_shift_pct: Shift as a percentage of image width (e.g., 0.1 = 10% shift right)

    img_array = np.array(image)
    height, width = img_array.shape[:2]

    h_shift_px = int(width * h_shift_pct)

    # Translation matrix:
    # [1, 0, h_shift_px] -> x_new = x + h_shift_px
    # [0, 1, 0         ] -> y_new = y (No vertical change)
    translation_matrix = np.array([[1, 0, h_shift_px], [0, 1, 0]], dtype=np.float32)

    translated = cv2.warpAffine(img_array, translation_matrix, (width, height),
                                borderMode=cv2.BORDER_CONSTANT, borderValue=(0, 0, 0))
    return Image.fromarray(translated)

#===================================================
# MOEA: NSGA-II
#===================================================


class PopulationLogger:
    def __init__(self, output_dir):
        self.output_dir = output_dir
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        self.csv_filename = os.path.join(output_dir, f"nsgaii_population_results_{timestamp}.csv")

        self.headers = [
            'Image_Name',
            'Generation',
            'Generation_Time_Seconds',
            'Solution_ID',
            'Obj1_Attack_Score',
            'Obj2_Distortion_Score',
            'Active_MMRs',
            'MMR1_Rotation', 'MMR2_Scale', 'MMR3_HistEq', 'MMR4_Downsample', 'MMR5_Shear', 'MMR6_Translate',
            'Original_Caption',
            'Original_Categories',
            'Transformed_Caption',
            'Transformed_Categories'
        ]
        self._initialize_csv()

    def _initialize_csv(self):
        os.makedirs(self.output_dir, exist_ok=True)
        with open(self.csv_filename, 'w', newline='') as f:
            writer = csv.writer(f)
            writer.writerow(self.headers)

    def log_population(self, solutions, image_name, generation, generation_time_seconds):
        with open(self.csv_filename, 'a', newline='') as f:
            writer = csv.writer(f)

            for i, sol in enumerate(solutions):
                mmr_config = sol.attributes.get('mmr_config', {})
                fitness_details = sol.attributes.get('fitness_details', {})
                vlm_outputs = fitness_details.get('vlm_outputs', {})

                obj1_score = -1.0 * sol.objectives[0]
                obj2_score = sol.objectives[1]

                row = [
                    image_name,
                    generation,
                    f"{generation_time_seconds:.6f}",
                    i,
                    f"{obj1_score:.6f}",
                    f"{obj2_score:.6f}",
                    fitness_details.get('active_count', 0),
                    str(mmr_config.get('rotation', {}).get('enabled', False)),
                    str(mmr_config.get('scale', {}).get('enabled', False)),
                    str(mmr_config.get('histogram_eq', {}).get('enabled', False)),
                    str(mmr_config.get('downsample', {}).get('enabled', False)),
                    str(mmr_config.get('shear', {}).get('enabled', False)),
                    str(mmr_config.get('translate', {}).get('enabled', False)),
                    vlm_outputs.get('original_caption', ''),
                    vlm_outputs.get('original_categories', ''),
                    vlm_outputs.get('final_caption', ''),
                    vlm_outputs.get('final_categories', '')
                ]
                writer.writerow(row)

    def get_csv_path(self):
        return self.csv_filename

# Generation observer for NSGA-II - storing all individuals details

from jmetal.util.observer import Observer
import numpy as np

class GenerationObserver(Observer):
    def __init__(self, logger, image_name, population_size):
        self.logger = logger
        self.image_name = image_name
        self.population_size = population_size
        self.last_time = time.time()

    def update(self, *args, **kwargs):
        evaluations = kwargs.get("EVALUATIONS", 0)
        solutions = kwargs.get("SOLUTIONS", [])

        if not solutions:
            return

        current_time = time.time()
        generation_time_seconds = current_time - self.last_time
        self.last_time = current_time

        generation = max(1, int(np.ceil(evaluations / self.population_size)))

        self.logger.log_population(
            solutions=solutions,
            image_name=self.image_name,
            generation=generation,
            generation_time_seconds=generation_time_seconds
        )

# ============================================================================
# PROBLEM DEFINITION (MULTI-OBJECTIVE)
# ============================================================================
class MetamorphicTestingProblem(FloatProblem):
    def number_of_objectives(self) -> int: return 2
    def number_of_constraints(self) -> int: return 0
    def number_of_variables(self) -> int: return 12
    def name(self) -> str: return "NSGAII_marineGPT"

    def __init__(self, dataset_images, output_dir):
        super(MetamorphicTestingProblem, self).__init__()
        # Bounds for 6 MMRs (Flag, Param)
        self.lower_bound = [0.0, -5.0, 0.0, 0.7, 0.0, 1.0, 0.0, 0.9, 0.0, -0.15, 0.0, -0.03]
        self.upper_bound = [1.0,  5.0, 1.0, 1.3, 1.0, 2.0, 1.0, 1.0, 1.0, 0.15, 1.0, 0.03]

        self.dataset_images = dataset_images
        self.output_dir = output_dir
        self.current_image_index = 0
        self.current_image_name = os.path.basename(self.dataset_images[0]) if self.dataset_images else None

    def evaluate(self, solution: FloatSolution) -> FloatSolution:
        variables = solution.variables
        mmr_config = self._parse_solution(variables)

        fitness_result = self._calculate_objectives(mmr_config)

        # NSGA-II Minimizes objectives by default
        # Objective 1: Attack Success (Maximize Conf Diff) -> Minimize (-Conf Diff)
        solution.objectives[0] = -1.0 * fitness_result['conf_diff_score']

        # Objective 2: Distortion (Minimize Magnitude) -> Minimize (Magnitude)
        solution.objectives[1] = fitness_result['avg_magnitude_total']

        # Store details for logging
        solution.attributes['fitness_details'] = fitness_result
        solution.attributes['mmr_config'] = mmr_config

        return solution

    def _parse_solution(self, variables):
        return {
            'rotation': {'enabled': variables[0] > 0.5, 'angle': variables[1]},
            'scale': {'enabled': variables[2] > 0.5, 'zoom_level': variables[3]},
            'histogram_eq': {'enabled': variables[4] > 0.5, 'clip_limit': variables[5]},
            'downsample': {'enabled': variables[6] > 0.5, 'scale_factor': variables[7]},
            'shear': {'enabled': variables[8] > 0.5, 'h_shear': variables[9], 'v_shear': 0.0},
            'translate': {'enabled': variables[10] > 0.5, 'h_shift_pct': variables[11], 'v_shift_pct': 0.0}
        }


    # applying horizontal + vertical both
    """
    def _get_param_magnitude(self, mmr_name, params):
        if mmr_name == 'rotation': return abs(params['angle']) / 5.0
        elif mmr_name == 'scale': return abs(params['zoom_level'] - 1.0) / 0.3
        elif mmr_name == 'histogram_eq': return abs(params['clip_limit'] - 1.0) / 1.0
        elif mmr_name == 'downsample': return abs(params['scale_factor'] - 1.0) / 0.1
        elif mmr_name == 'shear': return (abs(params['h_shear'])/0.15 + abs(params.get('v_shear',0))/0.3) / 2.0
        elif mmr_name == 'translate': return (abs(params['h_shift_pct'])/0.03 + abs(params.get('v_shift_pct',0))/0.05) / 2.0
        elif mmr_name == 'rgb2gray': return 0.5
        return 0.0
    """
    # applying only horizontal shifts
    def _get_param_magnitude(self, mmr_name, params):
        if mmr_name == 'rotation': return abs(params['angle']) / 5.0
        elif mmr_name == 'scale': return abs(params['zoom_level'] - 1.0) / 0.3
        elif mmr_name == 'histogram_eq': return abs(params['clip_limit'] - 1.0) / 1.0
        elif mmr_name == 'downsample': return abs(params['scale_factor'] - 1.0) / 0.1
        elif mmr_name == 'shear': return abs(params['h_shear'])/0.15
        elif mmr_name == 'translate': return abs(params['h_shift_pct'])/0.03
        return 0.0

    def _calculate_objectives(self, mmr_config):
        image_path = self.dataset_images[self.current_image_index]

        # 1. Original Prediction
        original_confidences = generate_marinegpt_prediction(Image.open(image_path).convert("RGB"))

        #print(f"VLM Output Original Image: Caption : {original_confidences['caption']}")
        #print(f"VLM Output Original Image: Counts  :   {original_confidences['categories']}")


        # 2. Apply Transformations
        current_image = Image.open(image_path).convert("RGB")
        active_count = 0
        total_normalized_magnitude = 0.0
        total_mmrs = 6.0

        def apply_and_track(key, func_call):
            nonlocal active_count, total_normalized_magnitude, current_image
            current_image = func_call
            active_count += 1
            total_normalized_magnitude += self._get_param_magnitude(key, mmr_config[key])

        if mmr_config['rotation']['enabled']:
            apply_and_track('rotation', rotate_image(current_image, mmr_config['rotation']['angle']))
        if mmr_config['scale']['enabled']:
            apply_and_track('scale', scale_image(current_image, mmr_config['scale']['zoom_level']))
        if mmr_config['histogram_eq']['enabled']:
            apply_and_track('histogram_eq', apply_histogram_equalization(current_image, mmr_config['histogram_eq']['clip_limit']))
        if mmr_config['downsample']['enabled']:
            apply_and_track('downsample', downsample_image(current_image, mmr_config['downsample']['scale_factor']))
        if mmr_config['shear']['enabled']:
            p = mmr_config['shear']
            apply_and_track('shear', shear_image(current_image, p['h_shear']))
        if mmr_config['translate']['enabled']:
            p = mmr_config['translate']
            apply_and_track('translate', translate_image(current_image, p['h_shift_pct']))

        # If no MMRs, minimal distortion but no attack
        if active_count == 0:
            return {
                'conf_diff_score': 0.0,
                'avg_magnitude_total': 0.0,
                'active_count': 0,
                'vlm_outputs': {
                'original_caption': original_confidences.get('caption', ''),
                'original_categories': ", ".join(
                    f"{cat}:{original_confidences['categories'].get(cat, 0)}" for cat in cat_names
                ),
                'final_caption': original_confidences.get('caption', ''),
                'final_categories': ", ".join(
                    f"{cat}:{original_confidences['categories'].get(cat, 0)}" for cat in cat_names
                )
            }
            }

        # 3. Final Prediction
        final_confidences    = generate_marinegpt_prediction(current_image)
        #print(f"Final Image: {final_confidences['caption']}")


        # 4. Calculate Scores
        # Obj 1: Confidence Difference (0.0 to 1.0)
        #diff_sum = sum(abs(original_confidences.get(cat, 0) - final_confidences.get(cat, 0)) for cat in cat_names)
        #diff_sum = sum(abs(original_confidences[cat]["confidence"] - final_confidences[cat]["confidence"]) for cat in cat_names)
        # ✅ Replace with — raw sum of absolute object count differences
        avg_conf_diff = 0
        for cat in cat_names:
            orig = original_confidences['categories'].get(cat, 0)
            final = final_confidences['categories'].get(cat, 0)

            diff = abs(orig - final)
            avg_conf_diff += diff / (diff + 1)

        # Obj 2: Distortion (Average Magnitude over TOTAL MMRs) (0.0 to 1.0) = for 1+1 EA
        #avg_magnitude_total = total_normalized_magnitude / total_mmrs
        # No average: consistent with other objective = (0.0 to 1,5,10...infinity etc ) = for NSGA-II
        avg_magnitude_total = total_normalized_magnitude


        return {
        'conf_diff_score':      avg_conf_diff,
        'avg_magnitude_total':  avg_magnitude_total,
        'active_count':         active_count,
        'vlm_outputs': {
        'original_caption': original_confidences.get('caption', ''),
        'original_categories': ", ".join(
            f"{cat}:{original_confidences['categories'].get(cat, 0)}" for cat in cat_names
        ),
        'final_caption': final_confidences.get('caption', ''),
        'final_categories': ", ".join(
            f"{cat}:{final_confidences['categories'].get(cat, 0)}" for cat in cat_names
        )
    }
    }

# ============================================================================
# BLIP NSGA-II: MULTI-RUN FIX (10 runs)
# Keep the rest of the BLIP NSGA-II pipeline unchanged.
# This only wraps the existing per-image optimization in an outer run loop.
# Each run writes to its own subfolder, so the existing CSV structure is preserved.
# ============================================================================

def main():
    IMAGE_DIR = "/global/D1/homes/user_name/venv/blip/input/"
    OUTPUT_DIR = "/global/D1/homes/user_name/venv/blip/output/"
    POPULATION_SIZE = 30
    MAX_EVALUATIONS = 3000
    N_RUNS = 10

    if not os.path.exists(IMAGE_DIR):
        print(f"Error: {IMAGE_DIR} does not exist.")
        return

    image_files = sorted([
        str(f) for f in Path(IMAGE_DIR).glob("*")
        if f.suffix.lower() in [".jpg", ".png", ".jpeg"]
    ])

    if not image_files:
        print("No images found in directory.")
        return

    print(f"Found {len(image_files)} images. Starting BLIP NSGA-II for {N_RUNS} runs...")

    for run_id in range(1, N_RUNS + 1):
        print("\n" + "=" * 80)
        print(f"BLIP NSGA-II RUN {run_id}/{N_RUNS}")
        print("=" * 80)

        run_output_dir = os.path.join(OUTPUT_DIR, f"run_{run_id:02d}")
        os.makedirs(run_output_dir, exist_ok=True)

        problem = MetamorphicTestingProblem(
            dataset_images=image_files,
            output_dir=run_output_dir
        )

        logger = PopulationLogger(run_output_dir)

        for img_idx in range(len(image_files)):
            problem.current_image_index = img_idx
            problem.current_image_name = os.path.basename(image_files[img_idx])
            print(f"\nProcessing Image {img_idx + 1}/{len(image_files)}: {problem.current_image_name}")

            algorithm = NSGAII(
                problem=problem,
                population_size=POPULATION_SIZE,
                offspring_population_size=POPULATION_SIZE,
                mutation=PolynomialMutation(
                    probability=1.0 / problem.number_of_variables(),
                    distribution_index=10
                ),
                crossover=SBXCrossover(probability=0.9, distribution_index=15),
                selection=BinaryTournamentSelection(
                    comparator=RankingAndCrowdingDistanceComparator()
                ),
                termination_criterion=StoppingByEvaluations(
                    max_evaluations=MAX_EVALUATIONS
                )
            )
            generation_observer = GenerationObserver(
            logger=logger, image_name=problem.current_image_name, population_size=POPULATION_SIZE)
            algorithm.observable.register(generation_observer)

            gen_start_time = time.time()
            algorithm.run()
            generation_time_seconds = time.time() - gen_start_time

            solutions = algorithm.result()
            print(f"  Optimization finished. Found {len(solutions)} solutions in Pareto Front.")
            print(f"  Generation time: {generation_time_seconds:.2f} seconds")

            # KEEP EXACT SAME LOGGER CALL STYLE AS YOUR CURRENT BLIP NSGA-II CODE
            #logger.log_pareto_front(solutions, problem.current_image_name, generation_time_seconds)

            # Save best attack image exactly as before
            best_attack = max(solutions, key=lambda s: -s.objectives[0])

            best_vars = problem._parse_solution(best_attack.variables)
            img_path = image_files[img_idx]
            current_img = Image.open(img_path).convert("RGB")

            if best_vars['rotation']['enabled']:
                current_img = rotate_image(current_img, best_vars['rotation']['angle'])
            if best_vars['scale']['enabled']:
                current_img = scale_image(current_img, best_vars['scale']['zoom_level'])
            if best_vars['histogram_eq']['enabled']:
                current_img = apply_histogram_equalization(
                    current_img, best_vars['histogram_eq']['clip_limit']
                )
            if best_vars['downsample']['enabled']:
                current_img = downsample_image(
                    current_img, best_vars['downsample']['scale_factor']
                )
            if best_vars['shear']['enabled']:
                p = best_vars['shear']
                current_img = shear_image(current_img, p['h_shear'])
            if best_vars['translate']['enabled']:
                p = best_vars['translate']
                current_img = translate_image(current_img, p['h_shift_pct'])

            save_path = os.path.join(
                run_output_dir,
                "pareto_images",
                f"img_{img_idx}_best_attack.png"
            )
            os.makedirs(os.path.dirname(save_path), exist_ok=True)
            current_img.save(save_path)
            print(f"  Best attack image saved to: {save_path}")

        print(f"\nRun {run_id} complete. Results at {logger.get_csv_path()}")

    print(f"\nAll {N_RUNS} BLIP NSGA-II runs complete.")

if __name__ == "__main__":
    main()


#===========================================
# Random MMRs - BLIP
#===========================================

# ============================================================================
# BLIP RandomSet (jMetalPy-based)
# Exact replacement for the current RandomSet section.
# ============================================================================

