# -*- coding: utf-8 -*-
"""BLIP_NSGA_Random_Finalv3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NpkGPoJOuB8sT8Zk9jTev_aK-paig6Zi
"""

#from transformers import BlipProcessor, BlipForConditionalGeneration
from __future__ import annotations



from dataclasses import dataclass
from typing import Dict, Iterable, List, Optional, Tuple
import pandas as pd  
try:
    from jmetal.core.quality_indicator import HyperVolume, InvertedGenerationalDistance
except ImportError:
    from jmetal.component.quality_indicator import HyperVolume, InvertedGenerationalDistance



import matplotlib.pyplot as plt
import seaborn as sns # Optional, for nicer styling

import os
import sys
import copy
import json
import csv
import random
import numpy as np
import torch
import cv2
from PIL import Image
from datetime import datetime
from pathlib import Path
import time

# Fix for numpy/scipy incompatibility
#!pip install numpy==1.26.4 scipy==1.16.3 --force-reinstall

# jMetalPy imports
from jmetal.core.problem import FloatProblem
from jmetal.core.solution import FloatSolution
from jmetal.core.algorithm import Algorithm
from jmetal.util.comparator import ObjectiveComparator


# jMetalPy imports
from jmetal.algorithm.multiobjective.nsgaii import NSGAII
from jmetal.operator.crossover import SBXCrossover
from jmetal.operator.mutation import PolynomialMutation
from jmetal.operator.selection import BinaryTournamentSelection
from jmetal.util.comparator import RankingAndCrowdingDistanceComparator
from jmetal.util.termination_criterion import StoppingByEvaluations

from jmetal.algorithm.multiobjective.random_search import RandomSearch
from jmetal.core.problem import FloatProblem
from jmetal.core.solution import FloatSolution
from jmetal.util.termination_criterion import StoppingByEvaluations

# Generation observer for NSGA-II - storing all individuals details

from jmetal.util.observer import Observer
import numpy as np
import re
from transformers import InstructBlipProcessor, InstructBlipForConditionalGeneration

# device
if torch.cuda.is_available():
    device = torch.device("cuda:0")
elif torch.backends.mps.is_available() and torch.backends.mps.is_built():
    device = torch.device("mps")
else:
    device = torch.device("cpu")

MODEL_NAME = "Salesforce/instructblip-vicuna-7b"

processor = InstructBlipProcessor.from_pretrained(MODEL_NAME)
model = InstructBlipForConditionalGeneration.from_pretrained(
    MODEL_NAME,
    torch_dtype=torch.float16 if device.type == "cuda" else torch.float32,
    low_cpu_mem_usage=True
).to(device)
model.eval()

cat_names = ["Trash", "Objects", "Animal", "Vegetation"]

#CATEGORY_PROMPT = "Identify and list all visible objects in this underwater image in four categories: (1) Trash (2) Objects (3) Animals (4) Vegetation. For each category, list the detected items with counts. If a category is definitely absent, write None."
CATEGORY_PROMPT = "Identify and list all visible objects in this underwater image in four categories:1. Animals 2. Vegetation 3. Trash 4. Objects. For each category: list the objects with counts. If a category is absent, write 'None'."

ANIMAL_WORDS = {
    "fish", "fishes", "crab", "crabs", "jellyfish", "lobster", "lobsters", "octopus",
    "octopi", "shrimp", "squid", "stingray", "ray", "turtle", "turtles", "urchin",
    "urchins", "starfish", "shell", "shells", "sponge", "sponges", "coral", "corals",
    "animal", "animals"
}

VEGETATION_WORDS = {
    "plant", "plants", "algae", "seaweed", "seagrass", "grass", "kelp", "vegetation"
}

TRASH_WORDS = {
    "bag", "bags", "bottle", "bottles", "cup", "cups", "container", "containers",
    "wrapper", "wrappers", "lid", "lids", "net", "nets", "rope", "ropes", "pipe", "pipes",
    "cable", "cables", "clothing", "boot", "boots", "tire", "tires", "tyre", "tyres",
    "cardboard", "branch", "branches", "furniture", "wood", "paper", "tube", "tubes",
    "brick", "bricks", "wreckage", "trash", "garbage", "debris", "plastic", "plastics",
    "can", "cans"
}

OBJECT_WORDS = {
    "object", "objects", "rov", "vehicle", "boat", "barge", "submarine", "crane",
    "tool", "tools", "box", "boxes", "metal", "equipment"
}

NUMBER_WORDS = {
    "a": 1, "an": 1, "one": 1, "two": 2, "three": 3, "four": 4, "five": 5,
    "six": 6, "seven": 7, "eight": 8, "nine": 9, "ten": 10
}

def _word_to_num(token: str):
    token = token.strip().lower()
    if token.isdigit():
        return int(token)
    return NUMBER_WORDS.get(token)

def _parse_count_from_chunk(chunk: str) -> int:
    chunk = chunk.lower().strip()

    m = re.search(r"\b(\d+)\b", chunk)
    if m:
        return int(m.group(1))

    for w, v in NUMBER_WORDS.items():
        if re.search(rf"\b{re.escape(w)}\b", chunk):
            return v

    if chunk and chunk not in {"none", "no", "nothing", "not visible", "not present"}:
        return 1
    return 0

def _count_items_in_text(text: str, vocab: set) -> int:
    text = text.lower()
    total = 0

    # split by commas / semicolons
    chunks = re.split(r"[;,]", text)
    for chunk in chunks:
        if any(re.search(rf"\b{re.escape(word)}\b", chunk) for word in vocab):
            total += _parse_count_from_chunk(chunk)

    # fallback: if category word exists but no count was found, count as 1
    if total == 0 and any(re.search(rf"\b{re.escape(word)}\b", text) for word in vocab):
        total = 1

    return total

def extract_category_counts(blip_output: str) -> dict:
    """
    Returns:
        {"Trash": int, "Objects": int, "Animal": int, "Vegetation": int}
    """
    text = blip_output.strip()
    lower = text.lower()

    counts = {"Trash": 0, "Objects": 0, "Animal": 0, "Vegetation": 0}

    line_map = {
        "animals:": ("Animal", ANIMAL_WORDS),
        "vegetation:": ("Vegetation", VEGETATION_WORDS),
        "trash:": ("Trash", TRASH_WORDS),
        "objects:": ("Objects", OBJECT_WORDS),
    }

    found_structured = False

    for prefix, (cat, vocab) in line_map.items():
        if prefix in lower:
            found_structured = True
            part = lower.split(prefix, 1)[1]
            part = part.split("\n", 1)[0].strip()
            if part not in {"none", "no", "nothing", "not visible", "not present"}:
                counts[cat] = _count_items_in_text(part, vocab)

    # fallback if model does not follow requested 4-line format
    #print("Fallback Structure Detected...!")
    if not found_structured:
        counts["Animal"] = _count_items_in_text(lower, ANIMAL_WORDS)
        counts["Vegetation"] = _count_items_in_text(lower, VEGETATION_WORDS)
        counts["Trash"] = _count_items_in_text(lower, TRASH_WORDS)
        counts["Objects"] = _count_items_in_text(lower, OBJECT_WORDS)

    return counts

# ============================================================================
# UPDATED PREDICTION LOGIC
# ============================================================================

def generate_blip_prediction(image, question=CATEGORY_PROMPT, max_new_tokens=80):
    if isinstance(image, str):
        image = Image.open(image).convert("RGB")
    else:
        image = image.convert("RGB")

    if device.type == "cuda":
        inputs = processor(images=image, text=question, return_tensors="pt").to(device, torch.float16)
    else:
        inputs = processor(images=image, text=question, return_tensors="pt").to(device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False
        )

    generated_text = processor.batch_decode(outputs, skip_special_tokens=True)[0].strip()

    if generated_text.lower().startswith(question.lower()):
        generated_text = generated_text[len(question):].strip(": ").strip()

    category_counts = extract_category_counts(generated_text)

    return {
        "caption": generated_text,
        "categories": category_counts
    }

def generate_marinegpt_prediction(image, chat=None):
    return generate_blip_prediction(image)

# ============================================================================
# IMAGE TRANSFORMATION FUNCTIONS (MMR) - SAME AS BEFORE
# ============================================================================

def rotate_image(image: Image.Image, angle: float) -> Image.Image:
    return image.rotate(angle, expand=False, fillcolor=(0, 0, 0))

def scale_image(image: Image.Image, zoom_level: float) -> Image.Image:
    width, height = image.size
    new_width = int(width * zoom_level)
    new_height = int(height * zoom_level)
    resized = image.resize((new_width, new_height), Image.LANCZOS)
    if zoom_level > 1.0:
        left = (new_width - width) // 2
        top = (new_height - height) // 2
        return resized.crop((left, top, left + width, top + height))
    else:
        new_image = Image.new('RGB', (width, height), (0, 0, 0))
        paste_x = (width - new_width) // 2
        paste_y = (height - new_height) // 2
        new_image.paste(resized, (paste_x, paste_y))
        return new_image

def apply_histogram_equalization(image: Image.Image, clip_limit: float) -> Image.Image:
    img_array = np.array(image)
    lab = cv2.cvtColor(img_array, cv2.COLOR_RGB2LAB)
    l, a, b = cv2.split(lab)
    clahe = cv2.createCLAHE(clipLimit=clip_limit, tileGridSize=(16, 16))
    l_clahe = clahe.apply(l)
    lab_clahe = cv2.merge([l_clahe, a, b])
    img_clahe = cv2.cvtColor(lab_clahe, cv2.COLOR_LAB2RGB)
    return Image.fromarray(img_clahe)

def downsample_image(image: Image.Image, scale_factor: float) -> Image.Image:
    width, height = image.size
    intermediate_w = int(width * scale_factor)
    intermediate_h = int(height * scale_factor)
    downsampled = image.resize((intermediate_w, intermediate_h), Image.NEAREST)
    return downsampled.resize((width, height), Image.NEAREST)

def shear_image(image: Image.Image, h_shear: float) -> Image.Image:

    # Applies only horizontal shear to the image.
    # h_shear: Shear factor (e.g., 0.2 means x' = x + 0.2*y)

    img_array = np.array(image)
    height, width = img_array.shape[:2]

    # Shear matrix:
    # [1, h_shear, 0] -> x_new = x + h_shear * y
    # [0, 1,       0] -> y_new = y (No vertical change)
    shear_matrix = np.array([[1, h_shear, 0], [0, 1, 0]], dtype=np.float32)

    sheared = cv2.warpAffine(img_array, shear_matrix, (width, height), borderMode=cv2.BORDER_CONSTANT, borderValue=(0, 0, 0))
    return Image.fromarray(sheared)

def translate_image(image: Image.Image, h_shift_pct: float) -> Image.Image:

    # Applies only horizontal translation to the image.
    # h_shift_pct: Shift as a percentage of image width (e.g., 0.1 = 10% shift right)

    img_array = np.array(image)
    height, width = img_array.shape[:2]

    h_shift_px = int(width * h_shift_pct)

    # Translation matrix:
    # [1, 0, h_shift_px] -> x_new = x + h_shift_px
    # [0, 1, 0         ] -> y_new = y (No vertical change)
    translation_matrix = np.array([[1, 0, h_shift_px], [0, 1, 0]], dtype=np.float32)

    translated = cv2.warpAffine(img_array, translation_matrix, (width, height),
                                borderMode=cv2.BORDER_CONSTANT, borderValue=(0, 0, 0))
    return Image.fromarray(translated)

#===================================================
# MOEA: NSGA-II
#===================================================


#===========================================
# Random MMRs - BLIP
#===========================================

# ============================================================================
# BLIP RandomSet (jMetalPy-based)
# Exact replacement for the current RandomSet section.
# ============================================================================




# ============================================================================
# MMR FUNCTIONS
# ============================================================================

MMR_FUNCTIONS = {
    'MMR1_Rotation':   rotate_image,
    'MMR2_Scale':      scale_image,
    'MMR3_HistEq':     apply_histogram_equalization,
    'MMR4_Downsample': downsample_image,
    'MMR5_Shear':      shear_image,
    'MMR6_Translate':  translate_image
}

RANDOM_MMR_ORDER = list(MMR_FUNCTIONS.keys())


# ============================================================================
# RANDOM PARAMETER GENERATION (unchanged)
# ============================================================================

def generate_random_params(mmr_name):
    if mmr_name == 'MMR1_Rotation':
        return {'angle': random.uniform(-5.0, 5.0)}
    elif mmr_name == 'MMR2_Scale':
        return {'zoom_level': random.uniform(0.7, 1.3)}
    elif mmr_name == 'MMR3_HistEq':
        return {'clip_limit': random.uniform(1.0, 3.0)}
    elif mmr_name == 'MMR4_Downsample':
        return {'scale_factor': random.uniform(0.9, 1.0)}
    elif mmr_name == 'MMR5_Shear':
        return {'h_shear': random.uniform(-0.15, 0.15)}
    elif mmr_name == 'MMR6_Translate':
        return {'h_shift_pct': random.uniform(-0.03, 0.03)}
    return {}


# ============================================================================
# FITNESS FUNCTION (same BLIP count-based logic as notebook)
# ============================================================================

def calculate_fitness(original_result, transformed_result, selected_mmrs, current_params, total_mmrs=6.0):
    
    #original_result/transformed_result:{"caption": str, "categories": {"Trash": int, "Objects": int, "Animal": int, "Vegetation": int}}
    #selected_mmrs: list of active MMR names , current_params:dict of sampled params for active MMRs
    

    def get_param_magnitude_random(mmr_name, params):
        if mmr_name == 'MMR1_Rotation':
            return abs(params['angle']) / 5.0
        elif mmr_name == 'MMR2_Scale':
            return abs(params['zoom_level'] - 1.0) / 0.3
        elif mmr_name == 'MMR3_HistEq':
            return abs(params['clip_limit'] - 1.0) / 1.0
        elif mmr_name == 'MMR4_Downsample':
            return abs(params['scale_factor'] - 1.0) / 0.1
        elif mmr_name == 'MMR5_Shear':
            return abs(params['h_shear']) / 0.15
        elif mmr_name == 'MMR6_Translate':
            return abs(params['h_shift_pct']) / 0.03
        return 0.0

    # Obj1: same BLIP attack score based on count changes
    obj1_attack_score = 0.0
    for cat in cat_names:
        orig_count = original_result['categories'].get(cat, 0)
        final_count = transformed_result['categories'].get(cat, 0)
        diff = abs(orig_count - final_count)
        obj1_attack_score += diff / (diff + 1)

    # Obj2: same distortion score
    total_normalized_magnitude = 0.0
    for mmr in selected_mmrs:
        total_normalized_magnitude += get_param_magnitude_random(mmr, current_params[mmr])

    obj2_distortion_score = total_normalized_magnitude

    # Removed below line. It was supposed for 1+1 EA
    #overall_fitness = (0.5 * obj1_attack_score) + (0.5 * (1.0 - obj2_distortion_score))

    return obj1_attack_score, obj2_distortion_score


# ============================================================================
# LOGGER (same CSV structure as current BLIP RandomSet notebook)
# ============================================================================

class MMRLogger:
    def __init__(self, output_dir):
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        self.filename = os.path.join(output_dir, f"blip_mmr_random_set_{timestamp}.csv")

        self.headers = [
            'Image_Name', 'Generation',
            'Selected_MMRs', 'Active_Count',
            'Overall_Fitness',
            'Obj1_Attack_Score',
            'Obj2_Distortion_Score',
            'MMR_Parameters',
            'Original_Caption',
            'Original_Categories',
            'Transformed_Caption',
            'Transformed_Categories',
        ]

        with open(self.filename, 'w', newline='') as f:
            csv.writer(f).writerow(self.headers)

    def log(self, data):
        with open(self.filename, 'a', newline='') as f:
            csv.writer(f).writerow([
                data['Image_Name'],
                data['Generation'],
                json.dumps(data['Selected_MMRs']),
                data['Active_Count'],
                f"{data['Overall_Fitness']:.6f}",
                f"{data['Obj1_Attack_Score']:.6f}",
                f"{data['Obj2_Distortion_Score']:.6f}",
                json.dumps(data['MMR_Parameters']),
                data['Original_Caption'],
                data['Original_Categories'],
                data['Transformed_Caption'],
                data['Transformed_Categories'],
            ])

    def get_csv_path(self):
        return self.filename

    # ============================================================================
    # HELPERS
    # ============================================================================

    def format_categories_string(result):
        return ", ".join(f"{cat}:{result['categories'].get(cat, 0)}" for cat in cat_names)

# ============================================================================
# jMetalPy PROBLEM
# Preserves the original RandomSet generation logic by sampling in create_solution()
# ============================================================================

class JMetalRandomMMRProblem(FloatProblem):
    def number_of_objectives(self) -> int:
        return 2

    def number_of_constraints(self) -> int:
        return 0

    def number_of_variables(self) -> int:
        return 12

    def name(self) -> str:
        return "BLIP_RandomSearch"

    def __init__(self, image_path, chat=None):
        super(JMetalRandomMMRProblem, self).__init__()

        self.image_path = image_path
        self.chat = chat

        # Bounds are needed by FloatSolution; actual random generation is handled in create_solution()
        self.lower_bound = [
            0.0, -5.0,    # rotation flag, angle
            0.0, 0.7,     # scale flag, zoom_level
            0.0, 1.0,     # hist eq flag, clip_limit
            0.0, 0.9,     # downsample flag, scale_factor
            0.0, -0.15,   # shear flag, h_shear
            0.0, -0.03    # translate flag, h_shift_pct
        ]

        self.upper_bound = [
            1.0, 5.0,
            1.0, 1.3,
            1.0, 3.0,
            1.0, 1.0,
            1.0, 0.15,
            1.0, 0.03
        ]

    def create_solution(self) -> FloatSolution:
        solution = FloatSolution(
            lower_bound=self.lower_bound,
            upper_bound=self.upper_bound,
            number_of_objectives=self.number_of_objectives()
        )

        # Neutral defaults for inactive MMRs
        variables = [
            0.0, 0.0,        # rotation off
            0.0, 1.0,        # scale off
            0.0, 1.0,        # hist eq off
            0.0, 1.0,        # downsample off
            0.0, 0.0,        # shear off
            0.0, 0.0         # translate off
        ]

        # Same random-set logic: random active-count + random subset
        num_mmrs = random.randint(1, len(RANDOM_MMR_ORDER))
        selected_mmrs = random.sample(RANDOM_MMR_ORDER, num_mmrs)

        mmr_params = {}

        for mmr in selected_mmrs:
            params = generate_random_params(mmr)
            mmr_params[mmr] = params

            if mmr == 'MMR1_Rotation':
                variables[0] = 1.0
                variables[1] = params['angle']
            elif mmr == 'MMR2_Scale':
                variables[2] = 1.0
                variables[3] = params['zoom_level']
            elif mmr == 'MMR3_HistEq':
                variables[4] = 1.0
                variables[5] = params['clip_limit']
            elif mmr == 'MMR4_Downsample':
                variables[6] = 1.0
                variables[7] = params['scale_factor']
            elif mmr == 'MMR5_Shear':
                variables[8] = 1.0
                variables[9] = params['h_shear']
            elif mmr == 'MMR6_Translate':
                variables[10] = 1.0
                variables[11] = params['h_shift_pct']

        solution.variables = variables

        # Important: preserve exact order and full RGB weights
        solution.attributes['selected_mmrs_order'] = selected_mmrs
        solution.attributes['sampled_mmr_params'] = mmr_params

        return solution

    def evaluate(self, solution: FloatSolution) -> FloatSolution:
        selected_mmrs = solution.attributes.get('selected_mmrs_order', [])
        sampled_params = solution.attributes.get('sampled_mmr_params', {})

        original_image = Image.open(self.image_path).convert("RGB")
        original_result = generate_marinegpt_prediction(original_image, self.chat)

        transformed_img = Image.open(self.image_path).convert("RGB")
        for mmr in selected_mmrs:
            transformed_img = MMR_FUNCTIONS[mmr](transformed_img, **sampled_params[mmr])

        transformed_result = generate_marinegpt_prediction(transformed_img, self.chat)

        obj1_attack_score, obj2_distortion_score = calculate_fitness(
            original_result=original_result,
            transformed_result=transformed_result,
            selected_mmrs=selected_mmrs,
            current_params=sampled_params,
            total_mmrs=len(RANDOM_MMR_ORDER)
        )

        # jMetalPy minimizes objectives
        solution.objectives[0] = -1.0 * obj1_attack_score
        solution.objectives[1] = obj2_distortion_score

        solution.attributes['overall_fitness'] = None
        solution.attributes['obj1_attack_score'] = obj1_attack_score
        solution.attributes['obj2_distortion_score'] = obj2_distortion_score
        solution.attributes['original_result'] = original_result
        solution.attributes['transformed_result'] = transformed_result
        solution.attributes['transformed_image'] = transformed_img

        return solution


# ============================================================================
# jMetalPy RandomSearch with per-evaluation CSV logging
# ============================================================================

class LoggedRandomSearch(RandomSearch):
    def __init__(self, problem, logger, image_name, output_dir, termination_criterion):
        super(LoggedRandomSearch, self).__init__(
            problem=problem,
            termination_criterion=termination_criterion
        )
        self.logger = logger
        self.image_name = image_name
        self.output_dir = output_dir
        self.best_fitness = -float("inf")
        self._initial_solution = None
        self._current_generation_start_time = None

    def evaluate(self, solution_list):
        evaluated = super(LoggedRandomSearch, self).evaluate(solution_list)
        self._initial_solution = evaluated[0]
        return evaluated

    def _log_solution(self, solution: FloatSolution, generation: int):
        selected_mmrs = solution.attributes['selected_mmrs_order']
        sampled_params = solution.attributes['sampled_mmr_params']
        original_result = solution.attributes['original_result']
        transformed_result = solution.attributes['transformed_result']

        overall_fitness = None
        obj1_attack_score = float(solution.attributes['obj1_attack_score'])
        obj2_distortion_score = float(solution.attributes['obj2_distortion_score'])

        self.logger.log({
            'Image_Name': self.image_name,
            'Generation': generation,
            'Selected_MMRs': selected_mmrs,
            'Active_Count': len(selected_mmrs),
            'Overall_Fitness': float("nan"),
            'Obj1_Attack_Score': obj1_attack_score,
            'Obj2_Distortion_Score': obj2_distortion_score,
            'MMR_Parameters': sampled_params,
            'Original_Caption': original_result['caption'],
            'Original_Categories': format_categories_string(original_result),
            'Transformed_Caption': transformed_result['caption'],
            'Transformed_Categories': format_categories_string(transformed_result),
        })

        status = "[Evaluated]"
        print(
            f"  Gen {generation}: "
            f"(Obj1: {obj1_attack_score:.4f}, Obj2: {obj2_distortion_score:.4f}, "
            f"Cnt: {len(selected_mmrs)}) {status}"
        )

    def init_progress(self) -> None:
        self.archive.add(self._initial_solution)
        self.evaluations = 1
        self._log_solution(self._initial_solution, generation=1)
        observable_data = self.observable_data()
        self.observable.notify_all(**observable_data)

    def step(self) -> None:
        self._current_generation_start_time = time.time()
        new_solution = self.problem.create_solution()
        self.problem.evaluate(new_solution)
        self.archive.add(new_solution)
        self._log_solution(new_solution, generation=self.evaluations + 1)
# ============================================================================
# HELPERS
# ============================================================================

def format_categories_string(result):
    return ", ".join(f"{cat}:{result['categories'].get(cat, 0)}" for cat in cat_names)


def save_random_pareto_front(front, image_name, output_dir):
    """
    Save the final non-dominated Pareto front found by Random Search.
    Objectives are stored in the same reporting format as NSGA-II:
        Obj1_Attack_Score = maximized attack score
        Obj2_Distortion_Score = minimized distortion score
    """

    pareto_dir = os.path.join(output_dir, "pareto_fronts")
    os.makedirs(pareto_dir, exist_ok=True)

    csv_path = os.path.join(
        pareto_dir,
        f"{Path(image_name).stem}_random_pareto_front.csv"
    )

    headers = [
        'Image_Name',
        'Pareto_ID',
        'Obj1_Attack_Score',
        'Obj2_Distortion_Score',
        'Selected_MMRs',
        'Active_Count',
        'MMR_Parameters',
        'Original_Caption',
        'Original_Categories',
        'Transformed_Caption',
        'Transformed_Categories'
    ]

    with open(csv_path, 'w', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(headers)

        for i, sol in enumerate(front):
            selected_mmrs = sol.attributes['selected_mmrs_order']
            sampled_params = sol.attributes['sampled_mmr_params']
            original_result = sol.attributes['original_result']
            transformed_result = sol.attributes['transformed_result']

            writer.writerow([
                image_name,
                i,
                f"{sol.attributes['obj1_attack_score']:.6f}",
                f"{sol.attributes['obj2_distortion_score']:.6f}",
                json.dumps(selected_mmrs),
                len(selected_mmrs),
                json.dumps(sampled_params),
                original_result['caption'],
                format_categories_string(original_result),
                transformed_result['caption'],
                format_categories_string(transformed_result),
            ])

            img_path = os.path.join(
                pareto_dir,
                f"{Path(image_name).stem}_pareto_{i}.png"
            )
            sol.attributes['transformed_image'].save(img_path)

    return csv_path

# ============================================================================
# MAIN RANDOM SEARCH EXECUTION (jMetalPy-based)
# ============================================================================

# ============================================================================
# BLIP RandomSet (jMetalPy): MULTI-RUN FIX (10 runs)
# Keep the rest of the BLIP RandomSet pipeline unchanged.
# This only adds the outer run loop and preserves the existing CSV structure.
# ============================================================================

def run_random_set_search_jmetalpy(chat, image_dir, output_dir, max_eval=3000, n_runs=10):
    image_files = sorted([
        f for f in os.listdir(image_dir)
        if f.lower().endswith((".jpg", ".png", ".jpeg"))
    ])

    if not image_files:
        print("No images found in directory.")
        return []

    print(f"Found {len(image_files)} images. Starting BLIP jMetalPy Random Search for {n_runs} runs...")

    all_csv_paths = []

    for run_id in range(1, n_runs + 1):
        print("\n" + "=" * 80)
        print(f"BLIP RANDOMSET RUN {run_id}/{n_runs}")
        print("=" * 80)

        run_output_dir = os.path.join(output_dir, f"run_{run_id:02d}")
        os.makedirs(run_output_dir, exist_ok=True)

        logger = MMRLogger(run_output_dir)

        for idx, img_name in enumerate(image_files):
            print(f"\nProcessing Image {idx + 1}/{len(image_files)}: {img_name}")
            img_path = os.path.join(image_dir, img_name)

            try:
                # KEEP EXACT SAME PREDICTION VALIDATION CALL AS YOUR CURRENT BLIP RANDOMSET CODE
                _ = generate_marinegpt_prediction(Image.open(img_path).convert("RGB"), chat)
            except Exception as e:
                print(f"Skipping {img_name}: Error loading image - {e}")
                continue

            problem = JMetalRandomMMRProblem(
                image_path=img_path,
                chat=chat
            )

            algorithm = LoggedRandomSearch(
                problem=problem,
                logger=logger,
                image_name=img_name,
                output_dir=run_output_dir,
                termination_criterion=StoppingByEvaluations(
                    max_evaluations=max_eval
                )
            )

            algorithm.run()

            front = algorithm.result()
            pareto_csv_path = save_random_pareto_front(
                front=front,
                image_name=img_name,
                output_dir=run_output_dir
            )
            
            print(f"  Non-dominated Random Search Pareto solutions: {len(front)}")
            print(f"  Pareto front saved to: {pareto_csv_path}")


        csv_path = logger.get_csv_path()
        all_csv_paths.append(csv_path)
        print(f"\nRun {run_id} complete. Results saved to: {csv_path}")

    print(f"\nAll {n_runs} BLIP RandomSet runs complete.")
    return all_csv_paths

# ============================================================================
# MAIN
# ============================================================================

if __name__ == "__main__":
    IMAGE_DIR = "/global/D1/homes/user_name/venv/blip/input/"
    OUTPUT_DIR = "/global/D1/homes/user_name/venv/blip/output/"

    if os.path.exists(IMAGE_DIR):
        run_random_set_search_jmetalpy(
            chat=None,
            image_dir=IMAGE_DIR,
            output_dir=OUTPUT_DIR,
            max_eval=3000,
             n_runs=10
        )
    else:
        print(f"Error: Image directory '{IMAGE_DIR}' not found.")

##############################################
# Randomset Visualization
#############################################

