# -*- coding: utf-8 -*-
"""CLIP_Random_Finalv0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13rxtxp0MG4s6XZxHEeZyhC5xLt4-sQ-D
"""

import os
import sys
import copy
import json
import csv
import random
import numpy as np
import torch
import cv2
import clip  # Added for MarineInsta
from PIL import Image
from datetime import datetime
from pathlib import Path
import time

# Fix for numpy/scipy incompatibility
#!pip install numpy==1.26.4 scipy==1.16.3 --force-reinstall

# jMetalPy imports
from jmetal.core.problem import FloatProblem
from jmetal.core.solution import FloatSolution
from jmetal.core.algorithm import Algorithm
from jmetal.util.comparator import ObjectiveComparator


from jmetal.algorithm.multiobjective.random_search import RandomSearch
from jmetal.core.problem import FloatProblem
from jmetal.core.solution import FloatSolution
from jmetal.util.termination_criterion import StoppingByEvaluations

# Generation observer for NSGA-II - storing all individuals details

from jmetal.util.observer import Observer

# jMetalPy imports
from jmetal.core.problem import FloatProblem
from jmetal.core.solution import FloatSolution
from jmetal.algorithm.multiobjective.nsgaii import NSGAII
from jmetal.operator.crossover import SBXCrossover
from jmetal.operator.mutation import PolynomialMutation
from jmetal.operator.selection import BinaryTournamentSelection
from jmetal.util.comparator import RankingAndCrowdingDistanceComparator
from jmetal.util.termination_criterion import StoppingByEvaluations


# Similarity check
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

# ============================================================================
# CONFIGURATION & SETUP
# ============================================================================

# Device setup
if torch.cuda.is_available():
    device = torch.device("cuda:0")
elif torch.backends.mps.is_available() and torch.backends.mps.is_built():
    device = torch.device("mps")
else:
    device = torch.device("cpu")

print(f"Using device: {device}")

# Load SBERT for Similarity Calculation (Used by MMT framework)
print("Loading SBERT model for similarity comparison...")
model_similarity = SentenceTransformer("all-MiniLM-L6-v2")

# ============================================================================
# MARINEINSTA VLM LOGIC (REPLACING BLIP)
# ============================================================================

# 1. MarineInsta uses CLIP ViT-L/14@336px
MODEL_TYPE = "ViT-L/14@336px"
print(f"Loading MarineInsta backbone ({MODEL_TYPE})...")
model_marine, preprocess_marine = clip.load(MODEL_TYPE, device=device)
model_marine.eval()

# 2. Define MarineInsta Categories & Prompts
# As per MarineInsta notebook:
MARINE_CATEGORIES = {
    "Trash": "plastic bottles, trash bags, marine debris, and garbage in water with count",
    "Objects": "diving equipment, ropes, nets, tools, and man-made structures with count",
    "Animal": "fish, sharks, turtles, dolphins, jellyfish, and sea creatures with count",
    "Vegetation": "seaweed, coral reefs, kelp, sea grass, and aquatic plants with count"
}

cat_names = list(MARINE_CATEGORIES.keys())
cat_descriptions = list(MARINE_CATEGORIES.values())
text_prompts = [f"an underwater image containing {desc}" for desc in cat_descriptions]

# Pre-compute text features (Optimization: Encode once)
print("Pre-computing text features for MarineInsta categories...")
with torch.no_grad():
    text_inputs = clip.tokenize(text_prompts).to(device)
    text_features_marine = model_marine.encode_text(text_inputs)
    text_features_marine /= text_features_marine.norm(dim=-1, keepdim=True)

# ============================================================================
# UPDATED PREDICTION LOGIC
# ============================================================================

def generate_vlm_prediction(image, model, preprocess, device):
    """
    Multi-label classification with proper calibration.
    Returns: dict {category_name: confidence_score}
    """
    if isinstance(image, str):
        image = Image.open(image).convert("RGB")
    else:
        image = image.convert("RGB")

    image_input = preprocess(image).unsqueeze(0).to(device)

    with torch.no_grad():
        image_features = model.encode_image(image_input)
        image_features /= image_features.norm(dim=-1, keepdim=True)

        # Raw cosine similarities (range: -1 to 1, typically 0.15-0.35 for positives)
        logits = (image_features @ text_features_marine.T)[0].cpu().numpy()

    scores = logits
    # Convert to probabilities using sigmoid with temperature scaling
    # Temperature = 10.0 prevents saturation while maintaining discrimination
    #scores = 1 / (1 + np.exp(-10.0 * logits))

    results = {cat: float(score) for cat, score in zip(cat_names, scores)}
    return results

###############CLIP Testing###############

# ============================================================================
# IMAGE TRANSFORMATION FUNCTIONS (MMR) - SAME AS BEFORE
# ============================================================================

def rotate_image(image: Image.Image, angle: float) -> Image.Image:
    return image.rotate(angle, expand=False, fillcolor=(0, 0, 0))

def scale_image(image: Image.Image, zoom_level: float) -> Image.Image:
    width, height = image.size
    new_width = int(width * zoom_level)
    new_height = int(height * zoom_level)
    resized = image.resize((new_width, new_height), Image.Resampling.LANCZOS)
    if zoom_level > 1.0:
        left = (new_width - width) // 2
        top = (new_height - height) // 2
        return resized.crop((left, top, left + width, top + height))
    else:
        new_image = Image.new('RGB', (width, height), (0, 0, 0))
        paste_x = (width - new_width) // 2
        paste_y = (height - new_height) // 2
        new_image.paste(resized, (paste_x, paste_y))
        return new_image

def apply_histogram_equalization(image: Image.Image, clip_limit: float) -> Image.Image:
    img_array = np.array(image)
    lab = cv2.cvtColor(img_array, cv2.COLOR_RGB2LAB)
    l, a, b = cv2.split(lab)
    clahe = cv2.createCLAHE(clipLimit=clip_limit, tileGridSize=(16, 16))
    l_clahe = clahe.apply(l)
    lab_clahe = cv2.merge([l_clahe, a, b])
    img_clahe = cv2.cvtColor(lab_clahe, cv2.COLOR_LAB2RGB)
    return Image.fromarray(img_clahe)

def downsample_image(image: Image.Image, scale_factor: float) -> Image.Image:
    width, height = image.size
    intermediate_w = int(width * scale_factor)
    intermediate_h = int(height * scale_factor)
    downsampled = image.resize((intermediate_w, intermediate_h), Image.Resampling.NEAREST)
    return downsampled.resize((width, height), Image.Resampling.NEAREST)

def shear_image(image: Image.Image, h_shear: float) -> Image.Image:

    # Applies only horizontal shear to the image.
    # h_shear: Shear factor (e.g., 0.2 means x' = x + 0.2*y)

    img_array = np.array(image)
    height, width = img_array.shape[:2]

    # Shear matrix:
    # [1, h_shear, 0] -> x_new = x + h_shear * y
    # [0, 1,       0] -> y_new = y (No vertical change)
    shear_matrix = np.array([[1, h_shear, 0], [0, 1, 0]], dtype=np.float32)

    sheared = cv2.warpAffine(img_array, shear_matrix, (width, height), borderMode=cv2.BORDER_CONSTANT, borderValue=(0, 0, 0))
    return Image.fromarray(sheared)

def translate_image(image: Image.Image, h_shift_pct: float) -> Image.Image:

    # Applies only horizontal translation to the image.
    # h_shift_pct: Shift as a percentage of image width (e.g., 0.1 = 10% shift right)

    img_array = np.array(image)
    height, width = img_array.shape[:2]

    h_shift_px = int(width * h_shift_pct)

    # Translation matrix:
    # [1, 0, h_shift_px] -> x_new = x + h_shift_px
    # [0, 1, 0         ] -> y_new = y (No vertical change)
    translation_matrix = np.array([[1, 0, h_shift_px], [0, 1, 0]], dtype=np.float32)

    translated = cv2.warpAffine(img_array, translation_matrix, (width, height),borderMode=cv2.BORDER_CONSTANT, borderValue=(0, 0, 0))
    return Image.fromarray(translated)

#===================================================
# MOEA: NSGA-II
#===================================================

##########################################
# Random by JMetalpy- GPT
########################################

# ============================================================================
# RANDOM SEARCH (jMetalPy-based replacement only)
# Keeps the existing metamorphic testing task, transformations, objectives,
# dataset handling, logging fields, and CSV structure.
# Does NOT modify the NSGA-II pipeline.
# ============================================================================


# Map transformation names to functions (unchanged)
MMR_FUNCTIONS = {
    'MMR1_Rotation': rotate_image,
    'MMR2_Scale': scale_image,
    'MMR3_HistEq': apply_histogram_equalization,
    'MMR4_Downsample': downsample_image,
    'MMR5_Shear': shear_image,
    'MMR6_Translate': translate_image
}

RANDOM_MMR_ORDER = list(MMR_FUNCTIONS.keys())


# ============================================================================
# ORIGINAL RANDOM PARAMETER GENERATION (kept)
# ============================================================================

def generate_random_params(mmr_name):
    if mmr_name == 'MMR1_Rotation':
        return {'angle': random.uniform(-5.0, 5.0)}
    elif mmr_name == 'MMR2_Scale':
        return {'zoom_level': random.uniform(0.7, 1.3)}
    elif mmr_name == 'MMR3_HistEq':
        return {'clip_limit': random.uniform(1.0, 3.0)}
    elif mmr_name == 'MMR4_Downsample':
        return {'scale_factor': random.uniform(0.9, 1.0)}
    elif mmr_name == 'MMR5_Shear':
        return {'h_shear': random.uniform(-0.15, 0.15)}
    elif mmr_name == 'MMR6_Translate':
        return {'h_shift_pct': random.uniform(-0.03, 0.03)}
    return {}


def get_param_magnitude(mmr_name, params):
    """
    Same distortion logic already used in the notebook's Random Search.
    """
    if mmr_name == 'rotation':
        return abs(params.get('angle', 0.0) - 0.0) / 5.0
    elif mmr_name == 'scale':
        return abs(params.get('zoom_level', 1.0) - 1.0) / 0.3
    elif mmr_name == 'histogram_eq':
        return abs(params.get('clip_limit', 1.0) - 1.0) / 1.0
    elif mmr_name == 'downsample':
        return abs(params.get('scale_factor', 1.0) - 1.0) / 0.1
    elif mmr_name == 'shear':
        return abs(params.get('h_shear', 0.0)) / 0.15
    elif mmr_name == 'translate':
        return abs(params.get('h_shift_pct', 0.0)) / 0.03
    return 0.0


def calculate_fitness(original_conf, transformed_conf, active_count, total_mmrs=6, mmr_params=None, selected_mmrs=None):
    """
    Same fitness definition already used in the notebook's Random Search.
    Obj1 = attack score
    Obj2 = distortion score
    Overall = 0.5 * Obj1 + 0.5 * (1 - Obj2)
    """
    if mmr_params is None:
        mmr_params = {}
    if selected_mmrs is None:
        selected_mmrs = []

    obj1_attack_score = 0.0
    for cat in cat_names:
        orig_conf = float(original_conf.get(cat, 0.0))
        trans_conf = float(transformed_conf.get(cat, 0.0))
        obj1_attack_score += abs(orig_conf - trans_conf)

    #obj1_attack_score = obj1_attack_score / 2.0

    total_normalized_magnitude = 0.0
    random_to_nsga_name = {
        'MMR1_Rotation': 'rotation',
        'MMR2_Scale': 'scale',
        'MMR3_HistEq': 'histogram_eq',
        'MMR4_Downsample': 'downsample',
        'MMR5_Shear': 'shear',
        'MMR6_Translate': 'translate'
    }

    for mmr in selected_mmrs:
        nsga_name = random_to_nsga_name[mmr]
        total_normalized_magnitude += get_param_magnitude(nsga_name, mmr_params[mmr])

    obj2_distortion_score = total_normalized_magnitude
    #overall_fitness = (0.5 * obj1_attack_score) + (0.5 * (1.0 - obj2_distortion_score))

    return obj1_attack_score, obj2_distortion_score


# ============================================================================
# LOGGER (kept compatible with existing Random Search CSV structure)
# ============================================================================

class MMRLogger:
    def __init__(self, output_dir):
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        self.filename = os.path.join(output_dir, f"CLIP_mmr_random_set_{timestamp}.csv")

        self.headers = [
            'Image_Name', 'Generation', 'Generation_Time_Seconds',
            'Selected_MMRs', 'Active_Count',
            'Overall_Fitness',
            'Obj1_Attack_Score',
            'Obj2_Distortion_Score',
            'MMR_Parameters',
            'Original_Confidence',
            'Transformed_Confidence'
        ]

        with open(self.filename, 'w', newline='') as f:
            writer = csv.writer(f)
            writer.writerow(self.headers)

    def log(self, data):
        with open(self.filename, 'a', newline='') as f:
            writer = csv.writer(f)
            row = [
                data['Image_Name'],
                data['Generation'],
                f"{data['Generation_Time_Seconds']:.6f}",
                json.dumps(data['Selected_MMRs']),
                data['Active_Count'],
                f"{data['Overall_Fitness']:.6f}",
                f"{data['Obj1_Attack_Score']:.6f}",
                f"{data['Obj2_Distortion_Score']:.6f}",
                json.dumps(data['MMR_Parameters']),
                json.dumps(data['Original_Confidence']),
                json.dumps(data['Transformed_Confidence'])
            ]
            writer.writerow(row)

    def get_csv_path(self):
        return self.filename

#============================================================================
# jMetalPy PROBLEM FOR RANDOM SEARCH
# Key point:
# - Uses jMetalPy FloatSolution so later HV/IGD can be computed in jMetalPy.
# - Preserves the ORIGINAL random MR generation logic by overriding create_solution().
# - Keeps the original random choice of:
#     * number of selected MMRs
#     * subset of selected MMRs
#     * sequential application order
#     * parameter sampling ranges
# ============================================================================

class JMetalRandomMMRProblem(FloatProblem):
    def number_of_objectives(self) -> int:
        return 2

    def number_of_constraints(self) -> int:
        return 0

    def number_of_variables(self) -> int:
        return 12

    def name(self) -> str:
        return "RandomSearch_MarineInsta"

    def __init__(self, model, preprocess, device, image_path):
        super(JMetalRandomMMRProblem, self).__init__()

        # Bounds are only used to build a valid FloatSolution.
        # They are set to cover the ORIGINAL random-search parameter ranges.
        self.lower_bound = [
            0.0, -5.0,   # flag, rotation angle
            0.0, 0.7,    # flag, scale
            0.0, 1.0,    # flag, hist eq
            0.0, 0.9,    # flag, downsample
            0.0, -0.15,  # flag, shear
            0.0, -0.03   # flag, translate
        ]
        self.upper_bound = [
            1.0, 5.0,
            1.0, 1.3,
            1.0, 2.0,
            1.0, 1.0,
            1.0, 0.15,
            1.0, 0.03
        ]

        self.model = model
        self.preprocess = preprocess
        self.device = device
        self.image_path = image_path

    def create_solution(self) -> FloatSolution:
        """
        This is the critical replacement:
        instead of ad hoc notebook sampling outside jMetalPy,
        we let the jMetalPy problem generate solutions that exactly follow
        the original Random Search sampling logic.
        """
        solution = FloatSolution(
            lower_bound=self.lower_bound,
            upper_bound=self.upper_bound,
            number_of_objectives=self.number_of_objectives()
        )

        # Neutral defaults for inactive MMRs
        variables = [
            0.0, 0.0,   # rotation off, angle neutral
            0.0, 1.0,   # scale off, neutral
            0.0, 1.0,   # hist eq off, neutral
            0.0, 1.0,   # downsample off, neutral
            0.0, 0.0,   # shear off, neutral
            0.0, 0.0    # translate off, neutral
        ]

        # Original logic: choose a random set size from 1..7, then random subset
        num_mmrs = random.randint(1, len(RANDOM_MMR_ORDER))
        selected_mmrs = random.sample(RANDOM_MMR_ORDER, num_mmrs)

        mmr_params = {}

        for mmr in selected_mmrs:
            params = generate_random_params(mmr)
            mmr_params[mmr] = params

            if mmr == 'MMR1_Rotation':
                variables[0] = 1.0
                variables[1] = params['angle']
            elif mmr == 'MMR2_Scale':
                variables[2] = 1.0
                variables[3] = params['zoom_level']
            elif mmr == 'MMR3_HistEq':
                variables[4] = 1.0
                variables[5] = params['clip_limit']
            elif mmr == 'MMR4_Downsample':
                variables[6] = 1.0
                variables[7] = params['scale_factor']
            elif mmr == 'MMR5_Shear':
                variables[8] = 1.0
                variables[9] = params['h_shear']
            elif mmr == 'MMR6_Translate':
                variables[10] = 1.0
                variables[11] = params['h_shift_pct']

        solution.variables = variables

        # Preserve information that cannot be reconstructed from the 14-D vector:
        # 1) random MMR order, because transformations are sequential and order matters
        # 2) exact RGB weights, because only one placeholder variable is stored in the vector
        solution.attributes['selected_mmrs_order'] = selected_mmrs
        solution.attributes['sampled_mmr_params'] = mmr_params

        return solution

    def evaluate(self, solution: FloatSolution) -> FloatSolution:
        selected_mmrs = solution.attributes.get('selected_mmrs_order', [])
        sampled_params = solution.attributes.get('sampled_mmr_params', {})

        original_conf = generate_vlm_prediction(
            self.image_path, self.model, self.preprocess, self.device
        )

        transformed_img = Image.open(self.image_path).convert("RGB")

        for mmr in selected_mmrs:
            params = sampled_params[mmr]
            transformed_img = MMR_FUNCTIONS[mmr](transformed_img, **params)

        transformed_conf = generate_vlm_prediction(
            transformed_img, self.model, self.preprocess, self.device
        )

        obj1_attack_score, obj2_distortion_score = calculate_fitness(
            original_conf=original_conf,
            transformed_conf=transformed_conf,
            active_count=len(selected_mmrs),
            total_mmrs=len(RANDOM_MMR_ORDER),
            mmr_params=sampled_params,
            selected_mmrs=selected_mmrs
        )

        # jMetalPy assumes minimization.
        # To maximize attack score fairly, store -Obj1 internally, exactly as done in NSGA-II.
        solution.objectives[0] = -1.0 * obj1_attack_score
        solution.objectives[1] = obj2_distortion_score

        # Keep raw outputs for logging / downstream analysis compatibility
        solution.attributes['overall_fitness'] = None
        solution.attributes['obj1_attack_score'] = obj1_attack_score
        solution.attributes['obj2_distortion_score'] = obj2_distortion_score
        solution.attributes['original_confidence'] = original_conf
        solution.attributes['transformed_confidence'] = transformed_conf
        solution.attributes['transformed_image'] = transformed_img

        return solution


# ============================================================================
# jMetalPy RANDOM SEARCH WITH PER-EVALUATION LOGGING
# The stock jMetalPy RandomSearch keeps a non-dominated archive.
# This subclass adds generation-wise CSV logging so your existing analysis
# pipeline remains usable.
# ============================================================================

class LoggedRandomSearch(RandomSearch):
    def __init__(self, problem, logger, image_name, output_dir, termination_criterion):
        super(LoggedRandomSearch, self).__init__(
            problem=problem,
            termination_criterion=termination_criterion
        )
        self.logger = logger
        self.image_name = image_name
        self.output_dir = output_dir
        self.best_fitness = -float("inf")
        self._initial_solution = None
        self._current_generation_start_time = None

    def evaluate(self, solution_list):
        evaluated = super(LoggedRandomSearch, self).evaluate(solution_list)
        self._initial_solution = evaluated[0]
        return evaluated

    def _log_solution(self, solution: FloatSolution, generation: int, generation_time_seconds: float):
        selected_mmrs = solution.attributes.get('selected_mmrs_order', [])
        mmr_params = solution.attributes.get('sampled_mmr_params', {})
        overall_fitness = None

        self.logger.log({
            'Image_Name': self.image_name,
            'Generation': generation,
            'Generation_Time_Seconds': generation_time_seconds,
            'Selected_MMRs': selected_mmrs,
            'Active_Count': len(selected_mmrs),
            'Overall_Fitness': float("nan"),
            'Obj1_Attack_Score': float(solution.attributes['obj1_attack_score']),
            'Obj2_Distortion_Score': float(solution.attributes['obj2_distortion_score']),
            'MMR_Parameters': mmr_params,
            'Original_Confidence': solution.attributes['original_confidence'],
            'Transformed_Confidence': solution.attributes['transformed_confidence']
        })

        save_path = os.path.join(
            self.output_dir,
            "transformed_images",
            f"{Path(self.image_name).stem}_gen{generation}.png"
        )

        status = "[EVALUATED]"
        os.makedirs(os.path.dirname(save_path), exist_ok=True)
        solution.attributes['transformed_image'].save(save_path)
        print(
            f"  Gen {generation}: "
            f"(Obj1: {solution.attributes['obj1_attack_score']:.4f}, "
            f"Obj2: {solution.attributes['obj2_distortion_score']:.4f}, "
            f"Time: {generation_time_seconds:.2f}s, "
            f"Cnt: {len(selected_mmrs)}) {status}"
        )

    def init_progress(self) -> None:
        self.archive.add(self._initial_solution)
        self.evaluations = 1
        self._log_solution(
            solution=self._initial_solution,
            generation=1,
            generation_time_seconds=0.0
        )
        observable_data = self.observable_data()
        self.observable.notify_all(**observable_data)

    def step(self) -> None:
        self._current_generation_start_time = time.time()
        new_solution = self.problem.create_solution()
        self.problem.evaluate(new_solution)
        self.archive.add(new_solution)

        generation_time_seconds = time.time() - self._current_generation_start_time
        self._log_solution(
            solution=new_solution,
            generation=self.evaluations + 1,
            generation_time_seconds=generation_time_seconds
        )

# ============================================================================
# HELPERS
# ============================================================================

def format_categories_string(result):
   return ", ".join(f"{cat}:{result['categories'].get(cat, 0)}" for cat in cat_names)


def save_random_pareto_front(front, image_name, output_dir):
   """
   Save the final non-dominated Pareto front found by Random Search.
   Objectives are stored in the same reporting format as NSGA-II:
       Obj1_Attack_Score = maximized attack score
       Obj2_Distortion_Score = minimized distortion score
   """


   pareto_dir = os.path.join(output_dir, "pareto_fronts")
   os.makedirs(pareto_dir, exist_ok=True)


   csv_path = os.path.join(
       pareto_dir,
       f"{Path(image_name).stem}_random_pareto_front.csv"
   )


   headers = [
       'Image_Name',
       'Pareto_ID',
       'Obj1_Attack_Score',
       'Obj2_Distortion_Score',
       'Selected_MMRs',
       'Active_Count',
       'MMR_Parameters',
       'Original_Confidence',
       'Transformed_Confidence'
   ]


   with open(csv_path, 'w', newline='') as f:
       writer = csv.writer(f)
       writer.writerow(headers)


       for i, sol in enumerate(front):
           selected_mmrs = sol.attributes['selected_mmrs_order']
           sampled_params = sol.attributes['sampled_mmr_params']
           original_result = sol.attributes['original_confidence']
           transformed_result = sol.attributes['transformed_confidence']


           writer.writerow([
               image_name,
               i,
               f"{sol.attributes['obj1_attack_score']:.6f}",
               f"{sol.attributes['obj2_distortion_score']:.6f}",
               json.dumps(selected_mmrs),
               len(selected_mmrs),
               json.dumps(sampled_params),
               original_result['original_confidence'],
               transformed_result['transformed_confidence'],
           ])


           img_path = os.path.join(
               pareto_dir,
               f"{Path(image_name).stem}_pareto_{i}.png"
           )
           sol.attributes['transformed_image'].save(img_path)


   return csv_path

# ============================================================================
# RandomSet: 10 runs, same CSV structure, one CSV per run
# ============================================================================

def run_random_set_search_jmetalpy(image_dir, output_dir, max_generations=3000, n_runs=10):
    image_files = sorted([
        f for f in os.listdir(image_dir)
        if f.lower().endswith((".jpg", ".png", ".jpeg"))
    ])

    print(f"Found {len(image_files)} images. Starting CLIP jMetalPy Random Search for {n_runs} runs...")

    all_csv_paths = []

    for run_id in range(1, n_runs + 1):
        print(f"\n{'=' * 80}")
        print(f"CLIP RANDOM SEARCH RUN {run_id}/{n_runs}")
        print(f"{'=' * 80}")

        run_output_dir = os.path.join(output_dir, f"run_{run_id:02d}")
        os.makedirs(run_output_dir, exist_ok=True)

        logger = MMRLogger(run_output_dir)

        for idx, img_name in enumerate(image_files):
            print(f"\nProcessing Image {idx + 1}/{len(image_files)}: {img_name}")
            img_path = os.path.join(image_dir, img_name)

            try:
                _ = generate_vlm_prediction(img_path, model_marine, preprocess_marine, device)
            except Exception as e:
                print(f"Skipping {img_name}: Error loading image - {e}")
                continue

            problem = JMetalRandomMMRProblem(
                model=model_marine,
                preprocess=preprocess_marine,
                device=device,
                image_path=img_path
            )

            algorithm = LoggedRandomSearch(
                problem=problem,
                logger=logger,
                image_name=img_name,
                output_dir=run_output_dir,
                termination_criterion=StoppingByEvaluations(
                    max_evaluations=max_generations
                )
            )

            algorithm.run()

            front = algorithm.result()
            print(f"  Non-dominated solutions kept by jMetalPy archive: {len(front)}")

        csv_path = logger.get_csv_path()
        all_csv_paths.append(csv_path)
        print(f"\nRun {run_id} complete. Results saved to: {csv_path}")

    print(f"\nAll {n_runs} Random Search runs complete.")
    return all_csv_paths

# ============================================================================
# MAIN - Randomset - 10 RUNS
# ============================================================================

IMAGE_DIR = "/global/D1/homes/user_name/venv/clip/input/"
OUTPUT_DIR = "/global/D1/homes/user_name/venv/clip/output/"
random_csvs = run_random_set_search_jmetalpy( IMAGE_DIR, OUTPUT_DIR, max_generations=3000, n_runs=10)

##########################################
# RQ1 - Results
########################################