# -*- coding: utf-8 -*-
"""CLIP_NSGA_Finalv0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mUCqGO98OS_qvaJRmcEbyNyO-I-0hES4
"""

import os
import sys
import copy
import json
import csv
import random
import numpy as np
import torch
import cv2
import clip  # Added for MarineInsta
from PIL import Image
from datetime import datetime
from pathlib import Path
import time

# Fix for numpy/scipy incompatibility
#!pip install numpy==1.26.4 scipy==1.16.3 --force-reinstall

# jMetalPy imports
from jmetal.core.problem import FloatProblem
from jmetal.core.solution import FloatSolution
from jmetal.core.algorithm import Algorithm
from jmetal.util.comparator import ObjectiveComparator


from jmetal.algorithm.multiobjective.random_search import RandomSearch
from jmetal.core.problem import FloatProblem
from jmetal.core.solution import FloatSolution
from jmetal.util.termination_criterion import StoppingByEvaluations

# Generation observer for NSGA-II - storing all individuals details

from jmetal.util.observer import Observer

# jMetalPy imports
from jmetal.core.problem import FloatProblem
from jmetal.core.solution import FloatSolution
from jmetal.algorithm.multiobjective.nsgaii import NSGAII
from jmetal.operator.crossover import SBXCrossover
from jmetal.operator.mutation import PolynomialMutation
from jmetal.operator.selection import BinaryTournamentSelection
from jmetal.util.comparator import RankingAndCrowdingDistanceComparator
from jmetal.util.termination_criterion import StoppingByEvaluations


# Similarity check
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

# ============================================================================
# CONFIGURATION & SETUP
# ============================================================================

# Device setup
if torch.cuda.is_available():
    device = torch.device("cuda:0")
elif torch.backends.mps.is_available() and torch.backends.mps.is_built():
    device = torch.device("mps")
else:
    device = torch.device("cpu")

print(f"Using device: {device}")

# Load SBERT for Similarity Calculation (Used by MMT framework)
print("Loading SBERT model for similarity comparison...")
model_similarity = SentenceTransformer("all-MiniLM-L6-v2")

# ============================================================================
# MARINEINSTA VLM LOGIC (REPLACING BLIP)
# ============================================================================

# 1. MarineInsta uses CLIP ViT-L/14@336px
MODEL_TYPE = "ViT-L/14@336px"
print(f"Loading MarineInsta backbone ({MODEL_TYPE})...")
model_marine, preprocess_marine = clip.load(MODEL_TYPE, device=device)
model_marine.eval()

# 2. Define MarineInsta Categories & Prompts
# As per MarineInsta notebook:
MARINE_CATEGORIES = {
    "Trash": "plastic bottles, trash bags, marine debris, and garbage in water with count",
    "Objects": "diving equipment, ropes, nets, tools, and man-made structures with count",
    "Animal": "fish, sharks, turtles, dolphins, jellyfish, and sea creatures with count",
    "Vegetation": "seaweed, coral reefs, kelp, sea grass, and aquatic plants with count"
}

cat_names = list(MARINE_CATEGORIES.keys())
cat_descriptions = list(MARINE_CATEGORIES.values())
text_prompts = [f"an underwater image containing {desc}" for desc in cat_descriptions]

# Pre-compute text features (Optimization: Encode once)
print("Pre-computing text features for MarineInsta categories...")
with torch.no_grad():
    text_inputs = clip.tokenize(text_prompts).to(device)
    text_features_marine = model_marine.encode_text(text_inputs)
    text_features_marine /= text_features_marine.norm(dim=-1, keepdim=True)

# ============================================================================
# UPDATED PREDICTION LOGIC
# ============================================================================

def generate_vlm_prediction(image, model, preprocess, device):
    """
    Multi-label classification with proper calibration.
    Returns: dict {category_name: confidence_score}
    """
    if isinstance(image, str):
        image = Image.open(image).convert("RGB")
    else:
        image = image.convert("RGB")

    image_input = preprocess(image).unsqueeze(0).to(device)

    with torch.no_grad():
        image_features = model.encode_image(image_input)
        image_features /= image_features.norm(dim=-1, keepdim=True)

        # Raw cosine similarities (range: -1 to 1, typically 0.15-0.35 for positives)
        logits = (image_features @ text_features_marine.T)[0].cpu().numpy()

    scores = logits
    # Convert to probabilities using sigmoid with temperature scaling
    # Temperature = 10.0 prevents saturation while maintaining discrimination
    #scores = 1 / (1 + np.exp(-10.0 * logits))

    results = {cat: float(score) for cat, score in zip(cat_names, scores)}
    return results

###############CLIP Testing###############

# ============================================================================
# IMAGE TRANSFORMATION FUNCTIONS (MMR) - SAME AS BEFORE
# ============================================================================

def rotate_image(image: Image.Image, angle: float) -> Image.Image:
    return image.rotate(angle, expand=False, fillcolor=(0, 0, 0))

def scale_image(image: Image.Image, zoom_level: float) -> Image.Image:
    width, height = image.size
    new_width = int(width * zoom_level)
    new_height = int(height * zoom_level)
    resized = image.resize((new_width, new_height), Image.Resampling.LANCZOS)
    if zoom_level > 1.0:
        left = (new_width - width) // 2
        top = (new_height - height) // 2
        return resized.crop((left, top, left + width, top + height))
    else:
        new_image = Image.new('RGB', (width, height), (0, 0, 0))
        paste_x = (width - new_width) // 2
        paste_y = (height - new_height) // 2
        new_image.paste(resized, (paste_x, paste_y))
        return new_image

def apply_histogram_equalization(image: Image.Image, clip_limit: float) -> Image.Image:
    img_array = np.array(image)
    lab = cv2.cvtColor(img_array, cv2.COLOR_RGB2LAB)
    l, a, b = cv2.split(lab)
    clahe = cv2.createCLAHE(clipLimit=clip_limit, tileGridSize=(16, 16))
    l_clahe = clahe.apply(l)
    lab_clahe = cv2.merge([l_clahe, a, b])
    img_clahe = cv2.cvtColor(lab_clahe, cv2.COLOR_LAB2RGB)
    return Image.fromarray(img_clahe)

def downsample_image(image: Image.Image, scale_factor: float) -> Image.Image:
    width, height = image.size
    intermediate_w = int(width * scale_factor)
    intermediate_h = int(height * scale_factor)
    downsampled = image.resize((intermediate_w, intermediate_h), Image.Resampling.NEAREST)
    return downsampled.resize((width, height), Image.Resampling.NEAREST)

def shear_image(image: Image.Image, h_shear: float) -> Image.Image:

    # Applies only horizontal shear to the image.
    # h_shear: Shear factor (e.g., 0.2 means x' = x + 0.2*y)

    img_array = np.array(image)
    height, width = img_array.shape[:2]

    # Shear matrix:
    # [1, h_shear, 0] -> x_new = x + h_shear * y
    # [0, 1,       0] -> y_new = y (No vertical change)
    shear_matrix = np.array([[1, h_shear, 0], [0, 1, 0]], dtype=np.float32)

    sheared = cv2.warpAffine(img_array, shear_matrix, (width, height), borderMode=cv2.BORDER_CONSTANT, borderValue=(0, 0, 0))
    return Image.fromarray(sheared)

def translate_image(image: Image.Image, h_shift_pct: float) -> Image.Image:

    # Applies only horizontal translation to the image.
    # h_shift_pct: Shift as a percentage of image width (e.g., 0.1 = 10% shift right)

    img_array = np.array(image)
    height, width = img_array.shape[:2]

    h_shift_px = int(width * h_shift_pct)

    # Translation matrix:
    # [1, 0, h_shift_px] -> x_new = x + h_shift_px
    # [0, 1, 0         ] -> y_new = y (No vertical change)
    translation_matrix = np.array([[1, 0, h_shift_px], [0, 1, 0]], dtype=np.float32)

    translated = cv2.warpAffine(img_array, translation_matrix, (width, height),borderMode=cv2.BORDER_CONSTANT, borderValue=(0, 0, 0))
    return Image.fromarray(translated)

#===================================================
# MOEA: NSGA-II
#===================================================

# ============================================================================
# PARETO FRONT LOGGER
# ============================================================================
class PopulationLogger:
    def __init__(self, output_dir):
        self.output_dir = output_dir
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        self.csv_filename = os.path.join(output_dir, f"nsgaii_population_results_{timestamp}.csv")

        self.headers = [
            'Image_Name',
            'Generation',
            'Generation_Time_Seconds',
            'Solution_ID',
            'Obj1_Attack_Score',
            'Obj2_Distortion_Score',
            'Active_MMRs',
            'MMR1_Rotation', 'MMR2_Scale', 'MMR3_HistEq', 'MMR4_Downsample','MMR5_Shear', 'MMR6_Translate',
            'Original_Confidence',
            'Transformed_Confidence'
        ]
        self._initialize_csv()

    def _initialize_csv(self):
        os.makedirs(self.output_dir, exist_ok=True)
        with open(self.csv_filename, 'w', newline='') as f:
            writer = csv.writer(f)
            writer.writerow(self.headers)

    def log_population(self, solutions, image_name, generation, generation_time_seconds):
        with open(self.csv_filename, 'a', newline='') as f:
            writer = csv.writer(f)

            for i, sol in enumerate(solutions):
                mmr_config = sol.attributes.get('mmr_config', {})
                fitness_details = sol.attributes.get('fitness_details', {})
                vlm_outputs = fitness_details.get('vlm_outputs', {})

                obj1_score = -1.0 * sol.objectives[0]
                obj2_score = sol.objectives[1]

                row = [
                    image_name,
                    generation,
                    f"{generation_time_seconds:.6f}",
                    i,
                    f"{obj1_score:.6f}",
                    f"{obj2_score:.6f}",
                    fitness_details.get('active_count', 0),
                    str(mmr_config.get('rotation', {}).get('enabled', False)),
                    str(mmr_config.get('scale', {}).get('enabled', False)),
                    str(mmr_config.get('histogram_eq', {}).get('enabled', False)),
                    str(mmr_config.get('downsample', {}).get('enabled', False)),
                    str(mmr_config.get('shear', {}).get('enabled', False)),
                    str(mmr_config.get('translate', {}).get('enabled', False)),
                    json.dumps(vlm_outputs.get('original', {})),
                    json.dumps(vlm_outputs.get('final', {}))
                ]
                writer.writerow(row)

    def get_csv_path(self):
        return self.csv_filename

class GenerationObserver(Observer):
    def __init__(self, logger, image_name):
        self.logger = logger
        self.image_name = image_name
        self.last_time = time.time()

    def update(self, *args, **kwargs):
        evaluations = kwargs.get("EVALUATIONS", 0)
        solutions = kwargs.get("SOLUTIONS", [])

        if not solutions:
            return

        current_time = time.time()
        generation_time_seconds = current_time - self.last_time
        self.last_time = current_time

        # NSGA-II uses population_size evaluations per generation after initialization
        # generation 0/1 handling is kept simple and consistent for logging
        self.logger.log_population(
            solutions=solutions,
            image_name=self.image_name,
            generation=evaluations,
            generation_time_seconds=generation_time_seconds
        )

# ============================================================================
# PROBLEM DEFINITION (MULTI-OBJECTIVE)
# ============================================================================

class MetamorphicTestingProblem(FloatProblem):
    def number_of_objectives(self) -> int: return 2
    def number_of_constraints(self) -> int: return 0
    def number_of_variables(self) -> int: return 12
    def name(self) -> str: return "NSGAII_MarineInsta"

    def __init__(self, model, preprocess, device, dataset_images, output_dir):
        super(MetamorphicTestingProblem, self).__init__()
        # Bounds for 6 MMRs (Flag, Param)
        self.lower_bound = [0.0, -5.0, 0.0, 0.7, 0.0, 1.0, 0.0, 0.9, 0.0, -0.15, 0.0, -0.03]
        self.upper_bound = [1.0, 5.0, 1.0, 1.3, 1.0, 2.0, 1.0, 1.0, 1.0, 0.15, 1.0, 0.03]

        self.model = model
        self.preprocess = preprocess
        self.device = device
        self.dataset_images = dataset_images
        self.output_dir = output_dir
        self.current_image_index = 0
        self.current_image_name = os.path.basename(self.dataset_images[0]) if self.dataset_images else None

    def evaluate(self, solution: FloatSolution) -> FloatSolution:
        variables = solution.variables
        mmr_config = self._parse_solution(variables)

        fitness_result = self._calculate_objectives(mmr_config)

        # NSGA-II Minimizes objectives by default
        # Objective 1: Attack Success (Maximize Conf Diff) -> Minimize (-Conf Diff)
        solution.objectives[0] = -1.0 * fitness_result['conf_diff_score']

        # Objective 2: Distortion (Minimize Magnitude) -> Minimize (Magnitude)
        solution.objectives[1] = fitness_result['avg_magnitude_total']

        # Store details for logging
        solution.attributes['fitness_details'] = fitness_result
        solution.attributes['mmr_config'] = mmr_config

        return solution

    def _parse_solution(self, variables):
        return {
            'rotation': {'enabled': variables[0] > 0.5, 'angle': variables[1]},
            'scale': {'enabled': variables[2] > 0.5, 'zoom_level': variables[3]},
            'histogram_eq': {'enabled': variables[4] > 0.5, 'clip_limit': variables[5]},
            'downsample': {'enabled': variables[6] > 0.5, 'scale_factor': variables[7]},
            'shear': {'enabled': variables[8] > 0.5, 'h_shear': variables[9], 'v_shear': 0.0},
            'translate': {'enabled': variables[10] > 0.5, 'h_shift_pct': variables[11], 'v_shift_pct': 0.0}
        }

    def _get_param_magnitude(self, mmr_name, params):
        if mmr_name == 'rotation': return abs(params['angle']) / 5.0
        elif mmr_name == 'scale': return abs(params['zoom_level'] - 1.0) / 0.3
        elif mmr_name == 'histogram_eq': return abs(params['clip_limit'] - 1.0) / 1.0
        elif mmr_name == 'downsample': return abs(params['scale_factor'] - 1.0) / 0.1
        elif mmr_name == 'shear': return abs(params['h_shear'])/0.15
        elif mmr_name == 'translate': return abs(params['h_shift_pct'])/0.03
        return 0.0

    def _calculate_objectives(self, mmr_config):
        image_path = self.dataset_images[self.current_image_index]

        # 1. Original Prediction
        original_confidences = generate_vlm_prediction(image_path, self.model, self.preprocess, self.device)

        # 2. Apply Transformations
        current_image = Image.open(image_path).convert("RGB")
        active_count = 0
        total_normalized_magnitude = 0.0
        total_mmrs = 6.0

        def apply_and_track(key, func_call):
            nonlocal active_count, total_normalized_magnitude, current_image
            current_image = func_call
            active_count += 1
            total_normalized_magnitude += self._get_param_magnitude(key, mmr_config[key])

        if mmr_config['rotation']['enabled']:
            apply_and_track('rotation', rotate_image(current_image, mmr_config['rotation']['angle']))
        if mmr_config['scale']['enabled']:
            apply_and_track('scale', scale_image(current_image, mmr_config['scale']['zoom_level']))
        if mmr_config['histogram_eq']['enabled']:
            apply_and_track('histogram_eq', apply_histogram_equalization(current_image, mmr_config['histogram_eq']['clip_limit']))
        if mmr_config['downsample']['enabled']:
            apply_and_track('downsample', downsample_image(current_image, mmr_config['downsample']['scale_factor']))
        if mmr_config['shear']['enabled']:
            p = mmr_config['shear']
            apply_and_track('shear', shear_image(current_image, p['h_shear']))
        if mmr_config['translate']['enabled']:
            p = mmr_config['translate']
            apply_and_track('translate', translate_image(current_image, p['h_shift_pct']))

        # If no MMRs, minimal distortion but no attack
        if active_count == 0:
            return {
                'conf_diff_score': 0.0,
                'avg_magnitude_total': 0.0,
                'active_count': 0,
                'vlm_outputs': {'original': original_confidences, 'final': original_confidences}
            }

        # 3. Final Prediction
        final_confidences = generate_vlm_prediction(current_image, self.model, self.preprocess, self.device)

        # 4. Calculate Scores
        # Obj 1: Confidence Difference (0.0 to 1.0)
        diff_sum = sum(abs(original_confidences.get(cat, 0) - final_confidences.get(cat, 0)) for cat in cat_names)
        avg_conf_diff = diff_sum

        # Obj 2: Distortion (Average Magnitude over TOTAL MMRs) (0.0 to 1.0)
        avg_magnitude_total = total_normalized_magnitude

        return {
            'conf_diff_score': avg_conf_diff,
            'avg_magnitude_total': avg_magnitude_total,
            'active_count': active_count,
            'vlm_outputs': {'original': original_confidences, 'final': final_confidences}
        }

# ============================================================================
# MAIN - NSGA-II - Single RUN
# ============================================================================

# ============================================================================
# NSGA-II: 10 runs, same CSV structure, one CSV per run
# ============================================================================

def main():
    IMAGE_DIR = "/global/D1/homes/user_name/venv/clip/input/"
    OUTPUT_DIR = "/global/D1/homes/user_name/venv/clip/output/"
    POPULATION_SIZE = 30
    MAX_EVALUATIONS = 3000
    N_RUNS = 10

    if not os.path.exists(IMAGE_DIR):
        print(f"Error: {IMAGE_DIR} does not exist.")
        return

    image_files = [
        str(f) for f in Path(IMAGE_DIR).glob("*")
        if f.suffix.lower() in [".jpg", ".png", ".jpeg"]
    ]
    image_files = sorted(image_files)

    if not image_files:
        print("No images found in directory.")
        return

    print(f"Found {len(image_files)} images. Starting NSGA-II for {N_RUNS} runs...")

    for run_id in range(1, N_RUNS + 1):
        print(f"\n{'=' * 80}")
        print(f"NSGA-II RUN {run_id}/{N_RUNS}")
        print(f"{'=' * 80}")

        run_output_dir = os.path.join(OUTPUT_DIR, f"run_{run_id:02d}")
        os.makedirs(run_output_dir, exist_ok=True)

        problem = MetamorphicTestingProblem(
            model=model_marine,
            preprocess=preprocess_marine,
            device=device,
            dataset_images=image_files,
            output_dir=OUTPUT_DIR
        )

        logger = PopulationLogger(run_output_dir)

        # >>> debugg this incase image_name is not stored instead of indexs
        for img_idx in range(len(image_files)):
            problem.current_image_index = img_idx
            problem.current_image_name = os.path.basename(image_files[img_idx])
            print(f"\nProcessing Image {img_idx + 1}/{len(image_files)}: {problem.current_image_name}")

            algorithm = NSGAII(
                problem=problem,
                population_size=POPULATION_SIZE,
                offspring_population_size=POPULATION_SIZE,
                mutation=PolynomialMutation(
                    probability=1.0 / problem.number_of_variables(),
                    distribution_index=10
                ),
                crossover=SBXCrossover(probability=0.9, distribution_index=15),
                selection=BinaryTournamentSelection(
                    comparator=RankingAndCrowdingDistanceComparator()
                ),
                termination_criterion=StoppingByEvaluations(
                    max_evaluations=MAX_EVALUATIONS
                )
            )
            #record each individual details
            generation_observer = GenerationObserver(logger=logger, image_name=problem.current_image_name)
            algorithm.observable.register(generation_observer)

            gen_start_time = time.time()
            algorithm.run()
            generation_time_seconds = time.time() - gen_start_time

            solutions = algorithm.result()
            print(f"  Optimization finished. Found {len(solutions)} solutions in Pareto Front.")
            print(f"  Generation time: {generation_time_seconds:.2f} seconds")

            # keep your existing CSV structure exactly as before
            #logger.log_pareto_front(solutions, img_idx, generation_time_seconds)

            best_attack = max(solutions, key=lambda s: -s.objectives[0])

            best_vars = problem._parse_solution(best_attack.variables)
            img_path = image_files[img_idx]
            current_img = Image.open(img_path).convert("RGB")

            if best_vars['rotation']['enabled']:
                current_img = rotate_image(current_img, best_vars['rotation']['angle'])
            if best_vars['scale']['enabled']:
                current_img = scale_image(current_img, best_vars['scale']['zoom_level'])
            if best_vars['histogram_eq']['enabled']:
                current_img = apply_histogram_equalization(
                    current_img, best_vars['histogram_eq']['clip_limit']
                )
            if best_vars['downsample']['enabled']:
                current_img = downsample_image(
                    current_img, best_vars['downsample']['scale_factor']
                )
            if best_vars['shear']['enabled']:
                p = best_vars['shear']
                current_img = shear_image(current_img, p['h_shear'])
            if best_vars['translate']['enabled']:
                p = best_vars['translate']
                current_img = translate_image(current_img, p['h_shift_pct'])

            save_path = os.path.join(
                run_output_dir, "pareto_images", f"img_{img_idx}_best_attack.png"
            )
            os.makedirs(os.path.dirname(save_path), exist_ok=True)
            current_img.save(save_path)
            print(f"  Best attack image saved to: {save_path}")

        print(f"\nRun {run_id} complete. Results at {logger.get_csv_path()}")

    print(f"\nAll {N_RUNS} NSGA-II runs complete.")

if __name__ == "__main__":
    main()

##########################################
# Random by JMetalpy- GPT
########################################

##########################################
# RQ1 - Results
########################################
